<?php
/**
 * ContinuePrintRequirementResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * ContinuePrintRequirementResponse Class Doc Comment
 *
 * @category Class
 * @description Guided completion state without persistence or matching execution.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ContinuePrintRequirementResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ContinuePrintRequirementResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'fulfilment' => '\Jawwws\Gnaww\Model\PublicFulfilmentState',
        'gjs' => '\Jawwws\Gnaww\Model\PrintJobSpecificationV04',
        'issues' => '\Jawwws\Gnaww\Model\IssueSet',
        'next_actions' => 'string[]',
        'persistence_performed' => 'bool',
        'producer_selection_performed' => 'bool',
        'product_family' => 'string',
        'questions' => '\Jawwws\Gnaww\Model\PublicClarificationQuestion[]',
        'recipe' => '\Jawwws\Gnaww\Model\PublicRecipeState',
        'remaining_question_keys' => 'string[]',
        'schema_name' => 'string',
        'schema_version' => 'string',
        'source' => '\Jawwws\Gnaww\Model\SourceInput',
        'specmatch' => '\Jawwws\Gnaww\Model\PublicSpecMatchReadiness',
        'specmatch_performed' => 'bool',
        'status' => 'string',
        'universe_match_ready' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'fulfilment' => null,
        'gjs' => null,
        'issues' => null,
        'next_actions' => null,
        'persistence_performed' => null,
        'producer_selection_performed' => null,
        'product_family' => null,
        'questions' => null,
        'recipe' => null,
        'remaining_question_keys' => null,
        'schema_name' => null,
        'schema_version' => null,
        'source' => null,
        'specmatch' => null,
        'specmatch_performed' => null,
        'status' => null,
        'universe_match_ready' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'fulfilment' => false,
        'gjs' => true,
        'issues' => false,
        'next_actions' => false,
        'persistence_performed' => false,
        'producer_selection_performed' => false,
        'product_family' => true,
        'questions' => false,
        'recipe' => false,
        'remaining_question_keys' => false,
        'schema_name' => false,
        'schema_version' => false,
        'source' => false,
        'specmatch' => false,
        'specmatch_performed' => false,
        'status' => false,
        'universe_match_ready' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fulfilment' => 'fulfilment',
        'gjs' => 'gjs',
        'issues' => 'issues',
        'next_actions' => 'next_actions',
        'persistence_performed' => 'persistence_performed',
        'producer_selection_performed' => 'producer_selection_performed',
        'product_family' => 'product_family',
        'questions' => 'questions',
        'recipe' => 'recipe',
        'remaining_question_keys' => 'remaining_question_keys',
        'schema_name' => 'schema_name',
        'schema_version' => 'schema_version',
        'source' => 'source',
        'specmatch' => 'specmatch',
        'specmatch_performed' => 'specmatch_performed',
        'status' => 'status',
        'universe_match_ready' => 'universe_match_ready'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fulfilment' => 'setFulfilment',
        'gjs' => 'setGjs',
        'issues' => 'setIssues',
        'next_actions' => 'setNextActions',
        'persistence_performed' => 'setPersistencePerformed',
        'producer_selection_performed' => 'setProducerSelectionPerformed',
        'product_family' => 'setProductFamily',
        'questions' => 'setQuestions',
        'recipe' => 'setRecipe',
        'remaining_question_keys' => 'setRemainingQuestionKeys',
        'schema_name' => 'setSchemaName',
        'schema_version' => 'setSchemaVersion',
        'source' => 'setSource',
        'specmatch' => 'setSpecmatch',
        'specmatch_performed' => 'setSpecmatchPerformed',
        'status' => 'setStatus',
        'universe_match_ready' => 'setUniverseMatchReady'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fulfilment' => 'getFulfilment',
        'gjs' => 'getGjs',
        'issues' => 'getIssues',
        'next_actions' => 'getNextActions',
        'persistence_performed' => 'getPersistencePerformed',
        'producer_selection_performed' => 'getProducerSelectionPerformed',
        'product_family' => 'getProductFamily',
        'questions' => 'getQuestions',
        'recipe' => 'getRecipe',
        'remaining_question_keys' => 'getRemainingQuestionKeys',
        'schema_name' => 'getSchemaName',
        'schema_version' => 'getSchemaVersion',
        'source' => 'getSource',
        'specmatch' => 'getSpecmatch',
        'specmatch_performed' => 'getSpecmatchPerformed',
        'status' => 'getStatus',
        'universe_match_ready' => 'getUniverseMatchReady'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PERSISTENCE_PERFORMED_FALSE = 'false';
    public const PRODUCER_SELECTION_PERFORMED_FALSE = 'false';
    public const PRODUCT_FAMILY_FLYER = 'flyer';
    public const PRODUCT_FAMILY_LEAFLET = 'leaflet';
    public const PRODUCT_FAMILY_FOLDED_LEAFLET = 'folded_leaflet';
    public const PRODUCT_FAMILY_APPAREL = 'apparel';
    public const PRODUCT_FAMILY_BUSINESS_CARD = 'business_card';
    public const PRODUCT_FAMILY_LOYALTY_CARD = 'loyalty_card';
    public const PRODUCT_FAMILY_POSTCARD = 'postcard';
    public const PRODUCT_FAMILY_POSTER = 'poster';
    public const PRODUCT_FAMILY_STICKER = 'sticker';
    public const PRODUCT_FAMILY_LABEL = 'label';
    public const PRODUCT_FAMILY_BOOKLET = 'booklet';
    public const PRODUCT_FAMILY_BOOK = 'book';
    public const PRODUCT_FAMILY_DOCUMENT = 'document';
    public const PRODUCT_FAMILY_CARD = 'card';
    public const PRODUCT_FAMILY_CERTIFICATE = 'certificate';
    public const PRODUCT_FAMILY_RACE_BIB = 'race_bib';
    public const PRODUCT_FAMILY_STATIONERY = 'stationery';
    public const PRODUCT_FAMILY_BOOKMARK = 'bookmark';
    public const PRODUCT_FAMILY_PRESENTATION_FOLDER = 'presentation_folder';
    public const PRODUCT_FAMILY_T_SHIRT = 't_shirt';
    public const PRODUCT_FAMILY_HOODIE = 'hoodie';
    public const PRODUCT_FAMILY_SWEATSHIRT = 'sweatshirt';
    public const PRODUCT_FAMILY_POLO_SHIRT = 'polo_shirt';
    public const PRODUCT_FAMILY_JACKET = 'jacket';
    public const PRODUCT_FAMILY_CAP = 'cap';
    public const PRODUCT_FAMILY_BEANIE = 'beanie';
    public const PRODUCT_FAMILY_WORKWEAR = 'workwear';
    public const PRODUCT_FAMILY_TEXTILE_ACCESSORY = 'textile_accessory';
    public const PRODUCT_FAMILY_CUSHION = 'cushion';
    public const PRODUCT_FAMILY_CUSHION_COVER = 'cushion_cover';
    public const PRODUCT_FAMILY_BEDDING = 'bedding';
    public const PRODUCT_FAMILY_CURTAIN = 'curtain';
    public const PRODUCT_FAMILY_TEA_TOWEL = 'tea_towel';
    public const PRODUCT_FAMILY_BLANKET = 'blanket';
    public const PRODUCT_FAMILY_FABRIC_BY_METRE = 'fabric_by_metre';
    public const PRODUCT_FAMILY_TABLECLOTH = 'tablecloth';
    public const PRODUCT_FAMILY_HOMEWARE = 'homeware';
    public const PRODUCT_FAMILY_PEN = 'pen';
    public const PRODUCT_FAMILY_MUG = 'mug';
    public const PRODUCT_FAMILY_WATER_BOTTLE = 'water_bottle';
    public const PRODUCT_FAMILY_GOLF_BALL = 'golf_ball';
    public const PRODUCT_FAMILY_UMBRELLA = 'umbrella';
    public const PRODUCT_FAMILY_BAG = 'bag';
    public const PRODUCT_FAMILY_NOTEBOOK = 'notebook';
    public const PRODUCT_FAMILY_LANYARD = 'lanyard';
    public const PRODUCT_FAMILY_KEYRING = 'keyring';
    public const PRODUCT_FAMILY_PROMOTIONAL_PRODUCT = 'promotional_product';
    public const PRODUCT_FAMILY_UNKNOWN = 'unknown';
    public const SCHEMA_NAME_GNAWW_INTERPRETATION_CONTINUATION_RESULT = 'gnaww.interpretation_continuation_result';
    public const SCHEMA_VERSION__0_1 = '0.1';
    public const SPECMATCH_PERFORMED_FALSE = 'false';
    public const STATUS_REVIEW_REQUIRED = 'review_required';
    public const STATUS_SPECMATCH_READY = 'specmatch_ready';
    public const STATUS_FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPersistencePerformedAllowableValues()
    {
        return [
            self::PERSISTENCE_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerSelectionPerformedAllowableValues()
    {
        return [
            self::PRODUCER_SELECTION_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProductFamilyAllowableValues()
    {
        return [
            self::PRODUCT_FAMILY_FLYER,
            self::PRODUCT_FAMILY_LEAFLET,
            self::PRODUCT_FAMILY_FOLDED_LEAFLET,
            self::PRODUCT_FAMILY_APPAREL,
            self::PRODUCT_FAMILY_BUSINESS_CARD,
            self::PRODUCT_FAMILY_LOYALTY_CARD,
            self::PRODUCT_FAMILY_POSTCARD,
            self::PRODUCT_FAMILY_POSTER,
            self::PRODUCT_FAMILY_STICKER,
            self::PRODUCT_FAMILY_LABEL,
            self::PRODUCT_FAMILY_BOOKLET,
            self::PRODUCT_FAMILY_BOOK,
            self::PRODUCT_FAMILY_DOCUMENT,
            self::PRODUCT_FAMILY_CARD,
            self::PRODUCT_FAMILY_CERTIFICATE,
            self::PRODUCT_FAMILY_RACE_BIB,
            self::PRODUCT_FAMILY_STATIONERY,
            self::PRODUCT_FAMILY_BOOKMARK,
            self::PRODUCT_FAMILY_PRESENTATION_FOLDER,
            self::PRODUCT_FAMILY_T_SHIRT,
            self::PRODUCT_FAMILY_HOODIE,
            self::PRODUCT_FAMILY_SWEATSHIRT,
            self::PRODUCT_FAMILY_POLO_SHIRT,
            self::PRODUCT_FAMILY_JACKET,
            self::PRODUCT_FAMILY_CAP,
            self::PRODUCT_FAMILY_BEANIE,
            self::PRODUCT_FAMILY_WORKWEAR,
            self::PRODUCT_FAMILY_TEXTILE_ACCESSORY,
            self::PRODUCT_FAMILY_CUSHION,
            self::PRODUCT_FAMILY_CUSHION_COVER,
            self::PRODUCT_FAMILY_BEDDING,
            self::PRODUCT_FAMILY_CURTAIN,
            self::PRODUCT_FAMILY_TEA_TOWEL,
            self::PRODUCT_FAMILY_BLANKET,
            self::PRODUCT_FAMILY_FABRIC_BY_METRE,
            self::PRODUCT_FAMILY_TABLECLOTH,
            self::PRODUCT_FAMILY_HOMEWARE,
            self::PRODUCT_FAMILY_PEN,
            self::PRODUCT_FAMILY_MUG,
            self::PRODUCT_FAMILY_WATER_BOTTLE,
            self::PRODUCT_FAMILY_GOLF_BALL,
            self::PRODUCT_FAMILY_UMBRELLA,
            self::PRODUCT_FAMILY_BAG,
            self::PRODUCT_FAMILY_NOTEBOOK,
            self::PRODUCT_FAMILY_LANYARD,
            self::PRODUCT_FAMILY_KEYRING,
            self::PRODUCT_FAMILY_PROMOTIONAL_PRODUCT,
            self::PRODUCT_FAMILY_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaNameAllowableValues()
    {
        return [
            self::SCHEMA_NAME_GNAWW_INTERPRETATION_CONTINUATION_RESULT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaVersionAllowableValues()
    {
        return [
            self::SCHEMA_VERSION__0_1,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSpecmatchPerformedAllowableValues()
    {
        return [
            self::SPECMATCH_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_REVIEW_REQUIRED,
            self::STATUS_SPECMATCH_READY,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fulfilment', $data ?? [], null);
        $this->setIfExists('gjs', $data ?? [], null);
        $this->setIfExists('issues', $data ?? [], null);
        $this->setIfExists('next_actions', $data ?? [], null);
        $this->setIfExists('persistence_performed', $data ?? [], false);
        $this->setIfExists('producer_selection_performed', $data ?? [], false);
        $this->setIfExists('product_family', $data ?? [], null);
        $this->setIfExists('questions', $data ?? [], null);
        $this->setIfExists('recipe', $data ?? [], null);
        $this->setIfExists('remaining_question_keys', $data ?? [], null);
        $this->setIfExists('schema_name', $data ?? [], 'gnaww.interpretation_continuation_result');
        $this->setIfExists('schema_version', $data ?? [], '0.1');
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('specmatch', $data ?? [], null);
        $this->setIfExists('specmatch_performed', $data ?? [], false);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('universe_match_ready', $data ?? [], false);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPersistencePerformedAllowableValues();
        if (!is_null($this->container['persistence_performed']) && !in_array($this->container['persistence_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'persistence_performed', must be one of '%s'",
                $this->container['persistence_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!is_null($this->container['producer_selection_performed']) && !in_array($this->container['producer_selection_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                $this->container['producer_selection_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProductFamilyAllowableValues();
        if (!is_null($this->container['product_family']) && !in_array($this->container['product_family'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'product_family', must be one of '%s'",
                $this->container['product_family'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['recipe'] === null) {
            $invalidProperties[] = "'recipe' can't be null";
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!is_null($this->container['schema_name']) && !in_array($this->container['schema_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_name', must be one of '%s'",
                $this->container['schema_name'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSchemaVersionAllowableValues();
        if (!is_null($this->container['schema_version']) && !in_array($this->container['schema_version'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_version', must be one of '%s'",
                $this->container['schema_version'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        if ($this->container['specmatch'] === null) {
            $invalidProperties[] = "'specmatch' can't be null";
        }
        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!is_null($this->container['specmatch_performed']) && !in_array($this->container['specmatch_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                $this->container['specmatch_performed'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fulfilment
     *
     * @return \Jawwws\Gnaww\Model\PublicFulfilmentState|null
     */
    public function getFulfilment()
    {
        return $this->container['fulfilment'];
    }

    /**
     * Sets fulfilment
     *
     * @param \Jawwws\Gnaww\Model\PublicFulfilmentState|null $fulfilment fulfilment
     *
     * @return self
     */
    public function setFulfilment($fulfilment)
    {
        if (is_null($fulfilment)) {
            throw new \InvalidArgumentException('non-nullable fulfilment cannot be null');
        }
        $this->container['fulfilment'] = $fulfilment;

        return $this;
    }

    /**
     * Gets gjs
     *
     * @return \Jawwws\Gnaww\Model\PrintJobSpecificationV04|null
     */
    public function getGjs()
    {
        return $this->container['gjs'];
    }

    /**
     * Sets gjs
     *
     * @param \Jawwws\Gnaww\Model\PrintJobSpecificationV04|null $gjs gjs
     *
     * @return self
     */
    public function setGjs($gjs)
    {
        if (is_null($gjs)) {
            array_push($this->openAPINullablesSetToNull, 'gjs');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gjs', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gjs'] = $gjs;

        return $this;
    }

    /**
     * Gets issues
     *
     * @return \Jawwws\Gnaww\Model\IssueSet|null
     */
    public function getIssues()
    {
        return $this->container['issues'];
    }

    /**
     * Sets issues
     *
     * @param \Jawwws\Gnaww\Model\IssueSet|null $issues issues
     *
     * @return self
     */
    public function setIssues($issues)
    {
        if (is_null($issues)) {
            throw new \InvalidArgumentException('non-nullable issues cannot be null');
        }
        $this->container['issues'] = $issues;

        return $this;
    }

    /**
     * Gets next_actions
     *
     * @return string[]|null
     */
    public function getNextActions()
    {
        return $this->container['next_actions'];
    }

    /**
     * Sets next_actions
     *
     * @param string[]|null $next_actions next_actions
     *
     * @return self
     */
    public function setNextActions($next_actions)
    {
        if (is_null($next_actions)) {
            throw new \InvalidArgumentException('non-nullable next_actions cannot be null');
        }
        $this->container['next_actions'] = $next_actions;

        return $this;
    }

    /**
     * Gets persistence_performed
     *
     * @return bool|null
     */
    public function getPersistencePerformed()
    {
        return $this->container['persistence_performed'];
    }

    /**
     * Sets persistence_performed
     *
     * @param bool|null $persistence_performed persistence_performed
     *
     * @return self
     */
    public function setPersistencePerformed($persistence_performed)
    {
        if (is_null($persistence_performed)) {
            throw new \InvalidArgumentException('non-nullable persistence_performed cannot be null');
        }
        $allowedValues = $this->getPersistencePerformedAllowableValues();
        if (!in_array($persistence_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'persistence_performed', must be one of '%s'",
                    $persistence_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['persistence_performed'] = $persistence_performed;

        return $this;
    }

    /**
     * Gets producer_selection_performed
     *
     * @return bool|null
     */
    public function getProducerSelectionPerformed()
    {
        return $this->container['producer_selection_performed'];
    }

    /**
     * Sets producer_selection_performed
     *
     * @param bool|null $producer_selection_performed producer_selection_performed
     *
     * @return self
     */
    public function setProducerSelectionPerformed($producer_selection_performed)
    {
        if (is_null($producer_selection_performed)) {
            throw new \InvalidArgumentException('non-nullable producer_selection_performed cannot be null');
        }
        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!in_array($producer_selection_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                    $producer_selection_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_selection_performed'] = $producer_selection_performed;

        return $this;
    }

    /**
     * Gets product_family
     *
     * @return string|null
     */
    public function getProductFamily()
    {
        return $this->container['product_family'];
    }

    /**
     * Sets product_family
     *
     * @param string|null $product_family product_family
     *
     * @return self
     */
    public function setProductFamily($product_family)
    {
        if (is_null($product_family)) {
            array_push($this->openAPINullablesSetToNull, 'product_family');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_family', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getProductFamilyAllowableValues();
        if (!is_null($product_family) && !in_array($product_family, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'product_family', must be one of '%s'",
                    $product_family,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['product_family'] = $product_family;

        return $this;
    }

    /**
     * Gets questions
     *
     * @return \Jawwws\Gnaww\Model\PublicClarificationQuestion[]|null
     */
    public function getQuestions()
    {
        return $this->container['questions'];
    }

    /**
     * Sets questions
     *
     * @param \Jawwws\Gnaww\Model\PublicClarificationQuestion[]|null $questions questions
     *
     * @return self
     */
    public function setQuestions($questions)
    {
        if (is_null($questions)) {
            throw new \InvalidArgumentException('non-nullable questions cannot be null');
        }
        $this->container['questions'] = $questions;

        return $this;
    }

    /**
     * Gets recipe
     *
     * @return \Jawwws\Gnaww\Model\PublicRecipeState
     */
    public function getRecipe()
    {
        return $this->container['recipe'];
    }

    /**
     * Sets recipe
     *
     * @param \Jawwws\Gnaww\Model\PublicRecipeState $recipe recipe
     *
     * @return self
     */
    public function setRecipe($recipe)
    {
        if (is_null($recipe)) {
            throw new \InvalidArgumentException('non-nullable recipe cannot be null');
        }
        $this->container['recipe'] = $recipe;

        return $this;
    }

    /**
     * Gets remaining_question_keys
     *
     * @return string[]|null
     */
    public function getRemainingQuestionKeys()
    {
        return $this->container['remaining_question_keys'];
    }

    /**
     * Sets remaining_question_keys
     *
     * @param string[]|null $remaining_question_keys remaining_question_keys
     *
     * @return self
     */
    public function setRemainingQuestionKeys($remaining_question_keys)
    {
        if (is_null($remaining_question_keys)) {
            throw new \InvalidArgumentException('non-nullable remaining_question_keys cannot be null');
        }
        $this->container['remaining_question_keys'] = $remaining_question_keys;

        return $this;
    }

    /**
     * Gets schema_name
     *
     * @return string|null
     */
    public function getSchemaName()
    {
        return $this->container['schema_name'];
    }

    /**
     * Sets schema_name
     *
     * @param string|null $schema_name schema_name
     *
     * @return self
     */
    public function setSchemaName($schema_name)
    {
        if (is_null($schema_name)) {
            throw new \InvalidArgumentException('non-nullable schema_name cannot be null');
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!in_array($schema_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_name', must be one of '%s'",
                    $schema_name,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_name'] = $schema_name;

        return $this;
    }

    /**
     * Gets schema_version
     *
     * @return string|null
     */
    public function getSchemaVersion()
    {
        return $this->container['schema_version'];
    }

    /**
     * Sets schema_version
     *
     * @param string|null $schema_version schema_version
     *
     * @return self
     */
    public function setSchemaVersion($schema_version)
    {
        if (is_null($schema_version)) {
            throw new \InvalidArgumentException('non-nullable schema_version cannot be null');
        }
        $allowedValues = $this->getSchemaVersionAllowableValues();
        if (!in_array($schema_version, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_version', must be one of '%s'",
                    $schema_version,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_version'] = $schema_version;

        return $this;
    }

    /**
     * Gets source
     *
     * @return \Jawwws\Gnaww\Model\SourceInput
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param \Jawwws\Gnaww\Model\SourceInput $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets specmatch
     *
     * @return \Jawwws\Gnaww\Model\PublicSpecMatchReadiness
     */
    public function getSpecmatch()
    {
        return $this->container['specmatch'];
    }

    /**
     * Sets specmatch
     *
     * @param \Jawwws\Gnaww\Model\PublicSpecMatchReadiness $specmatch specmatch
     *
     * @return self
     */
    public function setSpecmatch($specmatch)
    {
        if (is_null($specmatch)) {
            throw new \InvalidArgumentException('non-nullable specmatch cannot be null');
        }
        $this->container['specmatch'] = $specmatch;

        return $this;
    }

    /**
     * Gets specmatch_performed
     *
     * @return bool|null
     */
    public function getSpecmatchPerformed()
    {
        return $this->container['specmatch_performed'];
    }

    /**
     * Sets specmatch_performed
     *
     * @param bool|null $specmatch_performed specmatch_performed
     *
     * @return self
     */
    public function setSpecmatchPerformed($specmatch_performed)
    {
        if (is_null($specmatch_performed)) {
            throw new \InvalidArgumentException('non-nullable specmatch_performed cannot be null');
        }
        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!in_array($specmatch_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                    $specmatch_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['specmatch_performed'] = $specmatch_performed;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets universe_match_ready
     *
     * @return bool|null
     */
    public function getUniverseMatchReady()
    {
        return $this->container['universe_match_ready'];
    }

    /**
     * Sets universe_match_ready
     *
     * @param bool|null $universe_match_ready universe_match_ready
     *
     * @return self
     */
    public function setUniverseMatchReady($universe_match_ready)
    {
        if (is_null($universe_match_ready)) {
            throw new \InvalidArgumentException('non-nullable universe_match_ready cannot be null');
        }
        $this->container['universe_match_ready'] = $universe_match_ready;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
