<?php
/**
 * CustomDimensionCapability
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * CustomDimensionCapability Class Doc Comment
 *
 * @category Class
 * @description Supported limits for custom-sized production.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomDimensionCapability implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CustomDimensionCapability';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'increments_mm' => 'float[]',
        'maximum_depth_mm' => 'float',
        'maximum_diameter_mm' => 'float',
        'maximum_height_mm' => 'float',
        'maximum_width_mm' => 'float',
        'minimum_depth_mm' => 'float',
        'minimum_diameter_mm' => 'float',
        'minimum_height_mm' => 'float',
        'minimum_width_mm' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'increments_mm' => null,
        'maximum_depth_mm' => null,
        'maximum_diameter_mm' => null,
        'maximum_height_mm' => null,
        'maximum_width_mm' => null,
        'minimum_depth_mm' => null,
        'minimum_diameter_mm' => null,
        'minimum_height_mm' => null,
        'minimum_width_mm' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'increments_mm' => false,
        'maximum_depth_mm' => true,
        'maximum_diameter_mm' => true,
        'maximum_height_mm' => true,
        'maximum_width_mm' => true,
        'minimum_depth_mm' => true,
        'minimum_diameter_mm' => true,
        'minimum_height_mm' => true,
        'minimum_width_mm' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'increments_mm' => 'increments_mm',
        'maximum_depth_mm' => 'maximum_depth_mm',
        'maximum_diameter_mm' => 'maximum_diameter_mm',
        'maximum_height_mm' => 'maximum_height_mm',
        'maximum_width_mm' => 'maximum_width_mm',
        'minimum_depth_mm' => 'minimum_depth_mm',
        'minimum_diameter_mm' => 'minimum_diameter_mm',
        'minimum_height_mm' => 'minimum_height_mm',
        'minimum_width_mm' => 'minimum_width_mm'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'increments_mm' => 'setIncrementsMm',
        'maximum_depth_mm' => 'setMaximumDepthMm',
        'maximum_diameter_mm' => 'setMaximumDiameterMm',
        'maximum_height_mm' => 'setMaximumHeightMm',
        'maximum_width_mm' => 'setMaximumWidthMm',
        'minimum_depth_mm' => 'setMinimumDepthMm',
        'minimum_diameter_mm' => 'setMinimumDiameterMm',
        'minimum_height_mm' => 'setMinimumHeightMm',
        'minimum_width_mm' => 'setMinimumWidthMm'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'increments_mm' => 'getIncrementsMm',
        'maximum_depth_mm' => 'getMaximumDepthMm',
        'maximum_diameter_mm' => 'getMaximumDiameterMm',
        'maximum_height_mm' => 'getMaximumHeightMm',
        'maximum_width_mm' => 'getMaximumWidthMm',
        'minimum_depth_mm' => 'getMinimumDepthMm',
        'minimum_diameter_mm' => 'getMinimumDiameterMm',
        'minimum_height_mm' => 'getMinimumHeightMm',
        'minimum_width_mm' => 'getMinimumWidthMm'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('increments_mm', $data ?? [], null);
        $this->setIfExists('maximum_depth_mm', $data ?? [], null);
        $this->setIfExists('maximum_diameter_mm', $data ?? [], null);
        $this->setIfExists('maximum_height_mm', $data ?? [], null);
        $this->setIfExists('maximum_width_mm', $data ?? [], null);
        $this->setIfExists('minimum_depth_mm', $data ?? [], null);
        $this->setIfExists('minimum_diameter_mm', $data ?? [], null);
        $this->setIfExists('minimum_height_mm', $data ?? [], null);
        $this->setIfExists('minimum_width_mm', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['maximum_depth_mm']) && ($this->container['maximum_depth_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_depth_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['maximum_diameter_mm']) && ($this->container['maximum_diameter_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_diameter_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['maximum_height_mm']) && ($this->container['maximum_height_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_height_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['maximum_width_mm']) && ($this->container['maximum_width_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_width_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['minimum_depth_mm']) && ($this->container['minimum_depth_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'minimum_depth_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['minimum_diameter_mm']) && ($this->container['minimum_diameter_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'minimum_diameter_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['minimum_height_mm']) && ($this->container['minimum_height_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'minimum_height_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['minimum_width_mm']) && ($this->container['minimum_width_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'minimum_width_mm', must be bigger than 0.0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets increments_mm
     *
     * @return float[]|null
     */
    public function getIncrementsMm()
    {
        return $this->container['increments_mm'];
    }

    /**
     * Sets increments_mm
     *
     * @param float[]|null $increments_mm increments_mm
     *
     * @return self
     */
    public function setIncrementsMm($increments_mm)
    {
        if (is_null($increments_mm)) {
            throw new \InvalidArgumentException('non-nullable increments_mm cannot be null');
        }
        $this->container['increments_mm'] = $increments_mm;

        return $this;
    }

    /**
     * Gets maximum_depth_mm
     *
     * @return float|null
     */
    public function getMaximumDepthMm()
    {
        return $this->container['maximum_depth_mm'];
    }

    /**
     * Sets maximum_depth_mm
     *
     * @param float|null $maximum_depth_mm maximum_depth_mm
     *
     * @return self
     */
    public function setMaximumDepthMm($maximum_depth_mm)
    {
        if (is_null($maximum_depth_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_depth_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_depth_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_depth_mm) && ($maximum_depth_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_depth_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_depth_mm'] = $maximum_depth_mm;

        return $this;
    }

    /**
     * Gets maximum_diameter_mm
     *
     * @return float|null
     */
    public function getMaximumDiameterMm()
    {
        return $this->container['maximum_diameter_mm'];
    }

    /**
     * Sets maximum_diameter_mm
     *
     * @param float|null $maximum_diameter_mm maximum_diameter_mm
     *
     * @return self
     */
    public function setMaximumDiameterMm($maximum_diameter_mm)
    {
        if (is_null($maximum_diameter_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_diameter_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_diameter_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_diameter_mm) && ($maximum_diameter_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_diameter_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_diameter_mm'] = $maximum_diameter_mm;

        return $this;
    }

    /**
     * Gets maximum_height_mm
     *
     * @return float|null
     */
    public function getMaximumHeightMm()
    {
        return $this->container['maximum_height_mm'];
    }

    /**
     * Sets maximum_height_mm
     *
     * @param float|null $maximum_height_mm maximum_height_mm
     *
     * @return self
     */
    public function setMaximumHeightMm($maximum_height_mm)
    {
        if (is_null($maximum_height_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_height_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_height_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_height_mm) && ($maximum_height_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_height_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_height_mm'] = $maximum_height_mm;

        return $this;
    }

    /**
     * Gets maximum_width_mm
     *
     * @return float|null
     */
    public function getMaximumWidthMm()
    {
        return $this->container['maximum_width_mm'];
    }

    /**
     * Sets maximum_width_mm
     *
     * @param float|null $maximum_width_mm maximum_width_mm
     *
     * @return self
     */
    public function setMaximumWidthMm($maximum_width_mm)
    {
        if (is_null($maximum_width_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_width_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_width_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_width_mm) && ($maximum_width_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_width_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_width_mm'] = $maximum_width_mm;

        return $this;
    }

    /**
     * Gets minimum_depth_mm
     *
     * @return float|null
     */
    public function getMinimumDepthMm()
    {
        return $this->container['minimum_depth_mm'];
    }

    /**
     * Sets minimum_depth_mm
     *
     * @param float|null $minimum_depth_mm minimum_depth_mm
     *
     * @return self
     */
    public function setMinimumDepthMm($minimum_depth_mm)
    {
        if (is_null($minimum_depth_mm)) {
            array_push($this->openAPINullablesSetToNull, 'minimum_depth_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimum_depth_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($minimum_depth_mm) && ($minimum_depth_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_depth_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['minimum_depth_mm'] = $minimum_depth_mm;

        return $this;
    }

    /**
     * Gets minimum_diameter_mm
     *
     * @return float|null
     */
    public function getMinimumDiameterMm()
    {
        return $this->container['minimum_diameter_mm'];
    }

    /**
     * Sets minimum_diameter_mm
     *
     * @param float|null $minimum_diameter_mm minimum_diameter_mm
     *
     * @return self
     */
    public function setMinimumDiameterMm($minimum_diameter_mm)
    {
        if (is_null($minimum_diameter_mm)) {
            array_push($this->openAPINullablesSetToNull, 'minimum_diameter_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimum_diameter_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($minimum_diameter_mm) && ($minimum_diameter_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_diameter_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['minimum_diameter_mm'] = $minimum_diameter_mm;

        return $this;
    }

    /**
     * Gets minimum_height_mm
     *
     * @return float|null
     */
    public function getMinimumHeightMm()
    {
        return $this->container['minimum_height_mm'];
    }

    /**
     * Sets minimum_height_mm
     *
     * @param float|null $minimum_height_mm minimum_height_mm
     *
     * @return self
     */
    public function setMinimumHeightMm($minimum_height_mm)
    {
        if (is_null($minimum_height_mm)) {
            array_push($this->openAPINullablesSetToNull, 'minimum_height_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimum_height_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($minimum_height_mm) && ($minimum_height_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_height_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['minimum_height_mm'] = $minimum_height_mm;

        return $this;
    }

    /**
     * Gets minimum_width_mm
     *
     * @return float|null
     */
    public function getMinimumWidthMm()
    {
        return $this->container['minimum_width_mm'];
    }

    /**
     * Sets minimum_width_mm
     *
     * @param float|null $minimum_width_mm minimum_width_mm
     *
     * @return self
     */
    public function setMinimumWidthMm($minimum_width_mm)
    {
        if (is_null($minimum_width_mm)) {
            array_push($this->openAPINullablesSetToNull, 'minimum_width_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('minimum_width_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($minimum_width_mm) && ($minimum_width_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_width_mm when calling CustomDimensionCapability., must be bigger than 0.0.');
        }

        $this->container['minimum_width_mm'] = $minimum_width_mm;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
