<?php
/**
 * DecorationAreaCapability
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * DecorationAreaCapability Class Doc Comment
 *
 * @category Class
 * @description A reusable decoration position and size capability.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DecorationAreaCapability implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'DecorationAreaCapability';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'maximum_colours' => 'int',
        'maximum_diameter_mm' => 'float',
        'maximum_height_mm' => 'float',
        'maximum_width_mm' => 'float',
        'methods' => 'string[]',
        'position' => 'string',
        'supports_full_colour' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'maximum_colours' => null,
        'maximum_diameter_mm' => null,
        'maximum_height_mm' => null,
        'maximum_width_mm' => null,
        'methods' => null,
        'position' => null,
        'supports_full_colour' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'maximum_colours' => true,
        'maximum_diameter_mm' => true,
        'maximum_height_mm' => true,
        'maximum_width_mm' => true,
        'methods' => false,
        'position' => false,
        'supports_full_colour' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'maximum_colours' => 'maximum_colours',
        'maximum_diameter_mm' => 'maximum_diameter_mm',
        'maximum_height_mm' => 'maximum_height_mm',
        'maximum_width_mm' => 'maximum_width_mm',
        'methods' => 'methods',
        'position' => 'position',
        'supports_full_colour' => 'supports_full_colour'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'maximum_colours' => 'setMaximumColours',
        'maximum_diameter_mm' => 'setMaximumDiameterMm',
        'maximum_height_mm' => 'setMaximumHeightMm',
        'maximum_width_mm' => 'setMaximumWidthMm',
        'methods' => 'setMethods',
        'position' => 'setPosition',
        'supports_full_colour' => 'setSupportsFullColour'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'maximum_colours' => 'getMaximumColours',
        'maximum_diameter_mm' => 'getMaximumDiameterMm',
        'maximum_height_mm' => 'getMaximumHeightMm',
        'maximum_width_mm' => 'getMaximumWidthMm',
        'methods' => 'getMethods',
        'position' => 'getPosition',
        'supports_full_colour' => 'getSupportsFullColour'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const METHODS_DTG = 'dtg';
    public const METHODS_DTF = 'dtf';
    public const METHODS_HTV = 'htv';
    public const METHODS_EMBROIDERY = 'embroidery';
    public const METHODS_SCREEN_PRINT = 'screen_print';
    public const METHODS_SUBLIMATION = 'sublimation';
    public const METHODS_PAD_PRINT = 'pad_print';
    public const METHODS_UV_PRINT = 'uv_print';
    public const METHODS_ENGRAVING = 'engraving';
    public const METHODS_LASER_ENGRAVING = 'laser_engraving';
    public const METHODS_UNKNOWN = 'unknown';
    public const POSITION_FRONT = 'front';
    public const POSITION_BACK = 'back';
    public const POSITION_LEFT_CHEST = 'left_chest';
    public const POSITION_RIGHT_CHEST = 'right_chest';
    public const POSITION_SLEEVE = 'sleeve';
    public const POSITION_CAP_FRONT = 'cap_front';
    public const POSITION_LEFT = 'left';
    public const POSITION_RIGHT = 'right';
    public const POSITION_WRAP = 'wrap';
    public const POSITION_BARREL = 'barrel';
    public const POSITION_LID = 'lid';
    public const POSITION_BASE = 'base';
    public const POSITION_UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMethodsAllowableValues()
    {
        return [
            self::METHODS_DTG,
            self::METHODS_DTF,
            self::METHODS_HTV,
            self::METHODS_EMBROIDERY,
            self::METHODS_SCREEN_PRINT,
            self::METHODS_SUBLIMATION,
            self::METHODS_PAD_PRINT,
            self::METHODS_UV_PRINT,
            self::METHODS_ENGRAVING,
            self::METHODS_LASER_ENGRAVING,
            self::METHODS_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPositionAllowableValues()
    {
        return [
            self::POSITION_FRONT,
            self::POSITION_BACK,
            self::POSITION_LEFT_CHEST,
            self::POSITION_RIGHT_CHEST,
            self::POSITION_SLEEVE,
            self::POSITION_CAP_FRONT,
            self::POSITION_LEFT,
            self::POSITION_RIGHT,
            self::POSITION_WRAP,
            self::POSITION_BARREL,
            self::POSITION_LID,
            self::POSITION_BASE,
            self::POSITION_UNKNOWN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('maximum_colours', $data ?? [], null);
        $this->setIfExists('maximum_diameter_mm', $data ?? [], null);
        $this->setIfExists('maximum_height_mm', $data ?? [], null);
        $this->setIfExists('maximum_width_mm', $data ?? [], null);
        $this->setIfExists('methods', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('supports_full_colour', $data ?? [], false);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['maximum_colours']) && ($this->container['maximum_colours'] <= 0)) {
            $invalidProperties[] = "invalid value for 'maximum_colours', must be bigger than 0.";
        }

        if (!is_null($this->container['maximum_diameter_mm']) && ($this->container['maximum_diameter_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_diameter_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['maximum_height_mm']) && ($this->container['maximum_height_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_height_mm', must be bigger than 0.0.";
        }

        if (!is_null($this->container['maximum_width_mm']) && ($this->container['maximum_width_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'maximum_width_mm', must be bigger than 0.0.";
        }

        if ($this->container['methods'] === null) {
            $invalidProperties[] = "'methods' can't be null";
        }
        if ((count($this->container['methods']) < 1)) {
            $invalidProperties[] = "invalid value for 'methods', number of items must be greater than or equal to 1.";
        }

        if ($this->container['position'] === null) {
            $invalidProperties[] = "'position' can't be null";
        }
        $allowedValues = $this->getPositionAllowableValues();
        if (!is_null($this->container['position']) && !in_array($this->container['position'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'position', must be one of '%s'",
                $this->container['position'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets maximum_colours
     *
     * @return int|null
     */
    public function getMaximumColours()
    {
        return $this->container['maximum_colours'];
    }

    /**
     * Sets maximum_colours
     *
     * @param int|null $maximum_colours maximum_colours
     *
     * @return self
     */
    public function setMaximumColours($maximum_colours)
    {
        if (is_null($maximum_colours)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_colours');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_colours', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_colours) && ($maximum_colours <= 0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_colours when calling DecorationAreaCapability., must be bigger than 0.');
        }

        $this->container['maximum_colours'] = $maximum_colours;

        return $this;
    }

    /**
     * Gets maximum_diameter_mm
     *
     * @return float|null
     */
    public function getMaximumDiameterMm()
    {
        return $this->container['maximum_diameter_mm'];
    }

    /**
     * Sets maximum_diameter_mm
     *
     * @param float|null $maximum_diameter_mm maximum_diameter_mm
     *
     * @return self
     */
    public function setMaximumDiameterMm($maximum_diameter_mm)
    {
        if (is_null($maximum_diameter_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_diameter_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_diameter_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_diameter_mm) && ($maximum_diameter_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_diameter_mm when calling DecorationAreaCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_diameter_mm'] = $maximum_diameter_mm;

        return $this;
    }

    /**
     * Gets maximum_height_mm
     *
     * @return float|null
     */
    public function getMaximumHeightMm()
    {
        return $this->container['maximum_height_mm'];
    }

    /**
     * Sets maximum_height_mm
     *
     * @param float|null $maximum_height_mm maximum_height_mm
     *
     * @return self
     */
    public function setMaximumHeightMm($maximum_height_mm)
    {
        if (is_null($maximum_height_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_height_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_height_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_height_mm) && ($maximum_height_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_height_mm when calling DecorationAreaCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_height_mm'] = $maximum_height_mm;

        return $this;
    }

    /**
     * Gets maximum_width_mm
     *
     * @return float|null
     */
    public function getMaximumWidthMm()
    {
        return $this->container['maximum_width_mm'];
    }

    /**
     * Sets maximum_width_mm
     *
     * @param float|null $maximum_width_mm maximum_width_mm
     *
     * @return self
     */
    public function setMaximumWidthMm($maximum_width_mm)
    {
        if (is_null($maximum_width_mm)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_width_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_width_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_width_mm) && ($maximum_width_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_width_mm when calling DecorationAreaCapability., must be bigger than 0.0.');
        }

        $this->container['maximum_width_mm'] = $maximum_width_mm;

        return $this;
    }

    /**
     * Gets methods
     *
     * @return string[]
     */
    public function getMethods()
    {
        return $this->container['methods'];
    }

    /**
     * Sets methods
     *
     * @param string[] $methods methods
     *
     * @return self
     */
    public function setMethods($methods)
    {
        if (is_null($methods)) {
            throw new \InvalidArgumentException('non-nullable methods cannot be null');
        }
        $allowedValues = $this->getMethodsAllowableValues();
        if (array_diff($methods, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'methods', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($methods) < 1)) {
            throw new \InvalidArgumentException('invalid length for $methods when calling DecorationAreaCapability., number of items must be greater than or equal to 1.');
        }
        $this->container['methods'] = $methods;

        return $this;
    }

    /**
     * Gets position
     *
     * @return string
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param string $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            throw new \InvalidArgumentException('non-nullable position cannot be null');
        }
        $allowedValues = $this->getPositionAllowableValues();
        if (!in_array($position, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'position', must be one of '%s'",
                    $position,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets supports_full_colour
     *
     * @return bool|null
     */
    public function getSupportsFullColour()
    {
        return $this->container['supports_full_colour'];
    }

    /**
     * Sets supports_full_colour
     *
     * @param bool|null $supports_full_colour supports_full_colour
     *
     * @return self
     */
    public function setSupportsFullColour($supports_full_colour)
    {
        if (is_null($supports_full_colour)) {
            throw new \InvalidArgumentException('non-nullable supports_full_colour cannot be null');
        }
        $this->container['supports_full_colour'] = $supports_full_colour;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
