<?php
/**
 * FabricHomewaresOptions
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * FabricHomewaresOptions Class Doc Comment
 *
 * @category Class
 * @description Fabric and homewares production options.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FabricHomewaresOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'FabricHomewaresOptions';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'colour_profile' => 'string',
        'fastening_type' => 'string',
        'hem_style' => 'string',
        'lining_type' => 'string',
        'maximum_wash_temperature_c' => 'int',
        'print_method' => 'string',
        'repeat_height_mm' => 'float',
        'repeat_type' => 'string',
        'repeat_width_mm' => 'float',
        'wash_care' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'colour_profile' => null,
        'fastening_type' => null,
        'hem_style' => null,
        'lining_type' => null,
        'maximum_wash_temperature_c' => null,
        'print_method' => null,
        'repeat_height_mm' => null,
        'repeat_type' => null,
        'repeat_width_mm' => null,
        'wash_care' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'colour_profile' => false,
        'fastening_type' => false,
        'hem_style' => false,
        'lining_type' => false,
        'maximum_wash_temperature_c' => true,
        'print_method' => false,
        'repeat_height_mm' => true,
        'repeat_type' => false,
        'repeat_width_mm' => true,
        'wash_care' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'colour_profile' => 'colour_profile',
        'fastening_type' => 'fastening_type',
        'hem_style' => 'hem_style',
        'lining_type' => 'lining_type',
        'maximum_wash_temperature_c' => 'maximum_wash_temperature_c',
        'print_method' => 'print_method',
        'repeat_height_mm' => 'repeat_height_mm',
        'repeat_type' => 'repeat_type',
        'repeat_width_mm' => 'repeat_width_mm',
        'wash_care' => 'wash_care'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'colour_profile' => 'setColourProfile',
        'fastening_type' => 'setFasteningType',
        'hem_style' => 'setHemStyle',
        'lining_type' => 'setLiningType',
        'maximum_wash_temperature_c' => 'setMaximumWashTemperatureC',
        'print_method' => 'setPrintMethod',
        'repeat_height_mm' => 'setRepeatHeightMm',
        'repeat_type' => 'setRepeatType',
        'repeat_width_mm' => 'setRepeatWidthMm',
        'wash_care' => 'setWashCare'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'colour_profile' => 'getColourProfile',
        'fastening_type' => 'getFasteningType',
        'hem_style' => 'getHemStyle',
        'lining_type' => 'getLiningType',
        'maximum_wash_temperature_c' => 'getMaximumWashTemperatureC',
        'print_method' => 'getPrintMethod',
        'repeat_height_mm' => 'getRepeatHeightMm',
        'repeat_type' => 'getRepeatType',
        'repeat_width_mm' => 'getRepeatWidthMm',
        'wash_care' => 'getWashCare'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const COLOUR_PROFILE_SRGB = 'srgb';
    public const COLOUR_PROFILE_ADOBE_RGB = 'adobe_rgb';
    public const COLOUR_PROFILE_CMYK = 'cmyk';
    public const COLOUR_PROFILE_ICC_MANAGED = 'icc_managed';
    public const COLOUR_PROFILE_UNKNOWN = 'unknown';
    public const FASTENING_TYPE_NONE = 'none';
    public const FASTENING_TYPE_ZIP = 'zip';
    public const FASTENING_TYPE_CONCEALED_ZIP = 'concealed_zip';
    public const FASTENING_TYPE_BUTTONS = 'buttons';
    public const FASTENING_TYPE_TIES = 'ties';
    public const FASTENING_TYPE_EYELETS = 'eyelets';
    public const FASTENING_TYPE_HOOK_AND_LOOP = 'hook_and_loop';
    public const FASTENING_TYPE_ENVELOPE = 'envelope';
    public const FASTENING_TYPE_DRAWSTRING = 'drawstring';
    public const FASTENING_TYPE_UNKNOWN = 'unknown';
    public const HEM_STYLE_NONE = 'none';
    public const HEM_STYLE_OVERLOCKED = 'overlocked';
    public const HEM_STYLE_SINGLE_TURN = 'single_turn';
    public const HEM_STYLE_DOUBLE_TURN = 'double_turn';
    public const HEM_STYLE_ROLLED = 'rolled';
    public const HEM_STYLE_BLIND = 'blind';
    public const HEM_STYLE_UNKNOWN = 'unknown';
    public const LINING_TYPE_NONE = 'none';
    public const LINING_TYPE_STANDARD = 'standard';
    public const LINING_TYPE_BLACKOUT = 'blackout';
    public const LINING_TYPE_THERMAL = 'thermal';
    public const LINING_TYPE_INTERLINING = 'interlining';
    public const LINING_TYPE_UNKNOWN = 'unknown';
    public const PRINT_METHOD_DIGITAL_PRINT = 'digital_print';
    public const PRINT_METHOD_OFFSET_LITHO = 'offset_litho';
    public const PRINT_METHOD_LARGE_FORMAT = 'large_format';
    public const PRINT_METHOD_DTG = 'dtg';
    public const PRINT_METHOD_DTF = 'dtf';
    public const PRINT_METHOD_HTV = 'htv';
    public const PRINT_METHOD_EMBROIDERY = 'embroidery';
    public const PRINT_METHOD_SCREEN_PRINT = 'screen_print';
    public const PRINT_METHOD_SUBLIMATION = 'sublimation';
    public const PRINT_METHOD_DIGITAL_TEXTILE_PRINT = 'digital_textile_print';
    public const PRINT_METHOD_REACTIVE_DYE_PRINT = 'reactive_dye_print';
    public const PRINT_METHOD_PIGMENT_PRINT = 'pigment_print';
    public const PRINT_METHOD_SEWING = 'sewing';
    public const PRINT_METHOD_HEMMING = 'hemming';
    public const PRINT_METHOD_PAD_PRINT = 'pad_print';
    public const PRINT_METHOD_UV_PRINT = 'uv_print';
    public const PRINT_METHOD_ENGRAVING = 'engraving';
    public const PRINT_METHOD_LASER_ENGRAVING = 'laser_engraving';
    public const PRINT_METHOD_CUTTING = 'cutting';
    public const PRINT_METHOD_FOLDING = 'folding';
    public const PRINT_METHOD_BINDING = 'binding';
    public const PRINT_METHOD_LAMINATION = 'lamination';
    public const PRINT_METHOD_FOILING = 'foiling';
    public const PRINT_METHOD_SPOT_UV = 'spot_uv';
    public const PRINT_METHOD_UNKNOWN = 'unknown';
    public const REPEAT_TYPE_NONE = 'none';
    public const REPEAT_TYPE_STRAIGHT = 'straight';
    public const REPEAT_TYPE_HALF_DROP = 'half_drop';
    public const REPEAT_TYPE_MIRROR = 'mirror';
    public const REPEAT_TYPE_SEAMLESS = 'seamless';
    public const REPEAT_TYPE_ENGINEERED = 'engineered';
    public const REPEAT_TYPE_UNKNOWN = 'unknown';
    public const WASH_CARE_MACHINE_WASH = 'machine_wash';
    public const WASH_CARE_HAND_WASH = 'hand_wash';
    public const WASH_CARE_DRY_CLEAN = 'dry_clean';
    public const WASH_CARE_NOT_WASHABLE = 'not_washable';
    public const WASH_CARE_UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getColourProfileAllowableValues()
    {
        return [
            self::COLOUR_PROFILE_SRGB,
            self::COLOUR_PROFILE_ADOBE_RGB,
            self::COLOUR_PROFILE_CMYK,
            self::COLOUR_PROFILE_ICC_MANAGED,
            self::COLOUR_PROFILE_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFasteningTypeAllowableValues()
    {
        return [
            self::FASTENING_TYPE_NONE,
            self::FASTENING_TYPE_ZIP,
            self::FASTENING_TYPE_CONCEALED_ZIP,
            self::FASTENING_TYPE_BUTTONS,
            self::FASTENING_TYPE_TIES,
            self::FASTENING_TYPE_EYELETS,
            self::FASTENING_TYPE_HOOK_AND_LOOP,
            self::FASTENING_TYPE_ENVELOPE,
            self::FASTENING_TYPE_DRAWSTRING,
            self::FASTENING_TYPE_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getHemStyleAllowableValues()
    {
        return [
            self::HEM_STYLE_NONE,
            self::HEM_STYLE_OVERLOCKED,
            self::HEM_STYLE_SINGLE_TURN,
            self::HEM_STYLE_DOUBLE_TURN,
            self::HEM_STYLE_ROLLED,
            self::HEM_STYLE_BLIND,
            self::HEM_STYLE_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLiningTypeAllowableValues()
    {
        return [
            self::LINING_TYPE_NONE,
            self::LINING_TYPE_STANDARD,
            self::LINING_TYPE_BLACKOUT,
            self::LINING_TYPE_THERMAL,
            self::LINING_TYPE_INTERLINING,
            self::LINING_TYPE_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPrintMethodAllowableValues()
    {
        return [
            self::PRINT_METHOD_DIGITAL_PRINT,
            self::PRINT_METHOD_OFFSET_LITHO,
            self::PRINT_METHOD_LARGE_FORMAT,
            self::PRINT_METHOD_DTG,
            self::PRINT_METHOD_DTF,
            self::PRINT_METHOD_HTV,
            self::PRINT_METHOD_EMBROIDERY,
            self::PRINT_METHOD_SCREEN_PRINT,
            self::PRINT_METHOD_SUBLIMATION,
            self::PRINT_METHOD_DIGITAL_TEXTILE_PRINT,
            self::PRINT_METHOD_REACTIVE_DYE_PRINT,
            self::PRINT_METHOD_PIGMENT_PRINT,
            self::PRINT_METHOD_SEWING,
            self::PRINT_METHOD_HEMMING,
            self::PRINT_METHOD_PAD_PRINT,
            self::PRINT_METHOD_UV_PRINT,
            self::PRINT_METHOD_ENGRAVING,
            self::PRINT_METHOD_LASER_ENGRAVING,
            self::PRINT_METHOD_CUTTING,
            self::PRINT_METHOD_FOLDING,
            self::PRINT_METHOD_BINDING,
            self::PRINT_METHOD_LAMINATION,
            self::PRINT_METHOD_FOILING,
            self::PRINT_METHOD_SPOT_UV,
            self::PRINT_METHOD_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRepeatTypeAllowableValues()
    {
        return [
            self::REPEAT_TYPE_NONE,
            self::REPEAT_TYPE_STRAIGHT,
            self::REPEAT_TYPE_HALF_DROP,
            self::REPEAT_TYPE_MIRROR,
            self::REPEAT_TYPE_SEAMLESS,
            self::REPEAT_TYPE_ENGINEERED,
            self::REPEAT_TYPE_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWashCareAllowableValues()
    {
        return [
            self::WASH_CARE_MACHINE_WASH,
            self::WASH_CARE_HAND_WASH,
            self::WASH_CARE_DRY_CLEAN,
            self::WASH_CARE_NOT_WASHABLE,
            self::WASH_CARE_UNKNOWN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('colour_profile', $data ?? [], 'unknown');
        $this->setIfExists('fastening_type', $data ?? [], 'unknown');
        $this->setIfExists('hem_style', $data ?? [], 'unknown');
        $this->setIfExists('lining_type', $data ?? [], 'unknown');
        $this->setIfExists('maximum_wash_temperature_c', $data ?? [], null);
        $this->setIfExists('print_method', $data ?? [], 'unknown');
        $this->setIfExists('repeat_height_mm', $data ?? [], null);
        $this->setIfExists('repeat_type', $data ?? [], 'unknown');
        $this->setIfExists('repeat_width_mm', $data ?? [], null);
        $this->setIfExists('wash_care', $data ?? [], 'unknown');
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getColourProfileAllowableValues();
        if (!is_null($this->container['colour_profile']) && !in_array($this->container['colour_profile'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'colour_profile', must be one of '%s'",
                $this->container['colour_profile'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFasteningTypeAllowableValues();
        if (!is_null($this->container['fastening_type']) && !in_array($this->container['fastening_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fastening_type', must be one of '%s'",
                $this->container['fastening_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getHemStyleAllowableValues();
        if (!is_null($this->container['hem_style']) && !in_array($this->container['hem_style'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'hem_style', must be one of '%s'",
                $this->container['hem_style'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLiningTypeAllowableValues();
        if (!is_null($this->container['lining_type']) && !in_array($this->container['lining_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'lining_type', must be one of '%s'",
                $this->container['lining_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['maximum_wash_temperature_c']) && ($this->container['maximum_wash_temperature_c'] > 100)) {
            $invalidProperties[] = "invalid value for 'maximum_wash_temperature_c', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['maximum_wash_temperature_c']) && ($this->container['maximum_wash_temperature_c'] < 0)) {
            $invalidProperties[] = "invalid value for 'maximum_wash_temperature_c', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getPrintMethodAllowableValues();
        if (!is_null($this->container['print_method']) && !in_array($this->container['print_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'print_method', must be one of '%s'",
                $this->container['print_method'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['repeat_height_mm']) && ($this->container['repeat_height_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'repeat_height_mm', must be bigger than 0.0.";
        }

        $allowedValues = $this->getRepeatTypeAllowableValues();
        if (!is_null($this->container['repeat_type']) && !in_array($this->container['repeat_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'repeat_type', must be one of '%s'",
                $this->container['repeat_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['repeat_width_mm']) && ($this->container['repeat_width_mm'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'repeat_width_mm', must be bigger than 0.0.";
        }

        $allowedValues = $this->getWashCareAllowableValues();
        if (!is_null($this->container['wash_care']) && !in_array($this->container['wash_care'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'wash_care', must be one of '%s'",
                $this->container['wash_care'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets colour_profile
     *
     * @return string|null
     */
    public function getColourProfile()
    {
        return $this->container['colour_profile'];
    }

    /**
     * Sets colour_profile
     *
     * @param string|null $colour_profile colour_profile
     *
     * @return self
     */
    public function setColourProfile($colour_profile)
    {
        if (is_null($colour_profile)) {
            throw new \InvalidArgumentException('non-nullable colour_profile cannot be null');
        }
        $allowedValues = $this->getColourProfileAllowableValues();
        if (!in_array($colour_profile, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'colour_profile', must be one of '%s'",
                    $colour_profile,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['colour_profile'] = $colour_profile;

        return $this;
    }

    /**
     * Gets fastening_type
     *
     * @return string|null
     */
    public function getFasteningType()
    {
        return $this->container['fastening_type'];
    }

    /**
     * Sets fastening_type
     *
     * @param string|null $fastening_type fastening_type
     *
     * @return self
     */
    public function setFasteningType($fastening_type)
    {
        if (is_null($fastening_type)) {
            throw new \InvalidArgumentException('non-nullable fastening_type cannot be null');
        }
        $allowedValues = $this->getFasteningTypeAllowableValues();
        if (!in_array($fastening_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fastening_type', must be one of '%s'",
                    $fastening_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fastening_type'] = $fastening_type;

        return $this;
    }

    /**
     * Gets hem_style
     *
     * @return string|null
     */
    public function getHemStyle()
    {
        return $this->container['hem_style'];
    }

    /**
     * Sets hem_style
     *
     * @param string|null $hem_style hem_style
     *
     * @return self
     */
    public function setHemStyle($hem_style)
    {
        if (is_null($hem_style)) {
            throw new \InvalidArgumentException('non-nullable hem_style cannot be null');
        }
        $allowedValues = $this->getHemStyleAllowableValues();
        if (!in_array($hem_style, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'hem_style', must be one of '%s'",
                    $hem_style,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['hem_style'] = $hem_style;

        return $this;
    }

    /**
     * Gets lining_type
     *
     * @return string|null
     */
    public function getLiningType()
    {
        return $this->container['lining_type'];
    }

    /**
     * Sets lining_type
     *
     * @param string|null $lining_type lining_type
     *
     * @return self
     */
    public function setLiningType($lining_type)
    {
        if (is_null($lining_type)) {
            throw new \InvalidArgumentException('non-nullable lining_type cannot be null');
        }
        $allowedValues = $this->getLiningTypeAllowableValues();
        if (!in_array($lining_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'lining_type', must be one of '%s'",
                    $lining_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lining_type'] = $lining_type;

        return $this;
    }

    /**
     * Gets maximum_wash_temperature_c
     *
     * @return int|null
     */
    public function getMaximumWashTemperatureC()
    {
        return $this->container['maximum_wash_temperature_c'];
    }

    /**
     * Sets maximum_wash_temperature_c
     *
     * @param int|null $maximum_wash_temperature_c maximum_wash_temperature_c
     *
     * @return self
     */
    public function setMaximumWashTemperatureC($maximum_wash_temperature_c)
    {
        if (is_null($maximum_wash_temperature_c)) {
            array_push($this->openAPINullablesSetToNull, 'maximum_wash_temperature_c');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('maximum_wash_temperature_c', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($maximum_wash_temperature_c) && ($maximum_wash_temperature_c > 100)) {
            throw new \InvalidArgumentException('invalid value for $maximum_wash_temperature_c when calling FabricHomewaresOptions., must be smaller than or equal to 100.');
        }
        if (!is_null($maximum_wash_temperature_c) && ($maximum_wash_temperature_c < 0)) {
            throw new \InvalidArgumentException('invalid value for $maximum_wash_temperature_c when calling FabricHomewaresOptions., must be bigger than or equal to 0.');
        }

        $this->container['maximum_wash_temperature_c'] = $maximum_wash_temperature_c;

        return $this;
    }

    /**
     * Gets print_method
     *
     * @return string|null
     */
    public function getPrintMethod()
    {
        return $this->container['print_method'];
    }

    /**
     * Sets print_method
     *
     * @param string|null $print_method print_method
     *
     * @return self
     */
    public function setPrintMethod($print_method)
    {
        if (is_null($print_method)) {
            throw new \InvalidArgumentException('non-nullable print_method cannot be null');
        }
        $allowedValues = $this->getPrintMethodAllowableValues();
        if (!in_array($print_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'print_method', must be one of '%s'",
                    $print_method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['print_method'] = $print_method;

        return $this;
    }

    /**
     * Gets repeat_height_mm
     *
     * @return float|null
     */
    public function getRepeatHeightMm()
    {
        return $this->container['repeat_height_mm'];
    }

    /**
     * Sets repeat_height_mm
     *
     * @param float|null $repeat_height_mm repeat_height_mm
     *
     * @return self
     */
    public function setRepeatHeightMm($repeat_height_mm)
    {
        if (is_null($repeat_height_mm)) {
            array_push($this->openAPINullablesSetToNull, 'repeat_height_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('repeat_height_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($repeat_height_mm) && ($repeat_height_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $repeat_height_mm when calling FabricHomewaresOptions., must be bigger than 0.0.');
        }

        $this->container['repeat_height_mm'] = $repeat_height_mm;

        return $this;
    }

    /**
     * Gets repeat_type
     *
     * @return string|null
     */
    public function getRepeatType()
    {
        return $this->container['repeat_type'];
    }

    /**
     * Sets repeat_type
     *
     * @param string|null $repeat_type repeat_type
     *
     * @return self
     */
    public function setRepeatType($repeat_type)
    {
        if (is_null($repeat_type)) {
            throw new \InvalidArgumentException('non-nullable repeat_type cannot be null');
        }
        $allowedValues = $this->getRepeatTypeAllowableValues();
        if (!in_array($repeat_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'repeat_type', must be one of '%s'",
                    $repeat_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['repeat_type'] = $repeat_type;

        return $this;
    }

    /**
     * Gets repeat_width_mm
     *
     * @return float|null
     */
    public function getRepeatWidthMm()
    {
        return $this->container['repeat_width_mm'];
    }

    /**
     * Sets repeat_width_mm
     *
     * @param float|null $repeat_width_mm repeat_width_mm
     *
     * @return self
     */
    public function setRepeatWidthMm($repeat_width_mm)
    {
        if (is_null($repeat_width_mm)) {
            array_push($this->openAPINullablesSetToNull, 'repeat_width_mm');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('repeat_width_mm', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($repeat_width_mm) && ($repeat_width_mm <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $repeat_width_mm when calling FabricHomewaresOptions., must be bigger than 0.0.');
        }

        $this->container['repeat_width_mm'] = $repeat_width_mm;

        return $this;
    }

    /**
     * Gets wash_care
     *
     * @return string|null
     */
    public function getWashCare()
    {
        return $this->container['wash_care'];
    }

    /**
     * Sets wash_care
     *
     * @param string|null $wash_care wash_care
     *
     * @return self
     */
    public function setWashCare($wash_care)
    {
        if (is_null($wash_care)) {
            throw new \InvalidArgumentException('non-nullable wash_care cannot be null');
        }
        $allowedValues = $this->getWashCareAllowableValues();
        if (!in_array($wash_care, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'wash_care', must be one of '%s'",
                    $wash_care,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['wash_care'] = $wash_care;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
