<?php
/**
 * MatchPrintDemandUniverseResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * MatchPrintDemandUniverseResponse Class Doc Comment
 *
 * @category Class
 * @description Ranked capability result across an authorised producer universe.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MatchPrintDemandUniverseResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MatchPrintDemandUniverseResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'availability_checked' => 'bool',
        'best_capable_candidate' => '\Jawwws\Gnaww\Model\PublicProducerUniverseCandidate',
        'blocked_count' => 'int',
        'candidates' => '\Jawwws\Gnaww\Model\PublicProducerUniverseCandidate[]',
        'confirmed_capable_count' => 'int',
        'demand_basis' => 'string',
        'leading_candidate' => '\Jawwws\Gnaww\Model\PublicProducerUniverseCandidate',
        'live_pricing_performed' => 'bool',
        'next_actions' => 'string[]',
        'order_created' => 'bool',
        'outcome' => 'string',
        'persistence_performed' => 'bool',
        'producer_acceptance_performed' => 'bool',
        'producer_selection_performed' => 'bool',
        'producer_universe_evaluated' => 'bool',
        'producer_universe_size' => 'int',
        'ranking_performed' => 'bool',
        'readiness' => '\Jawwws\Gnaww\Model\PublicSpecMatchReadiness',
        'recipe' => '\Jawwws\Gnaww\Model\PublicRecipeState',
        'review_required_count' => 'int',
        'schema_name' => 'string',
        'schema_version' => 'string',
        'specmatch_performed' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'availability_checked' => null,
        'best_capable_candidate' => null,
        'blocked_count' => null,
        'candidates' => null,
        'confirmed_capable_count' => null,
        'demand_basis' => null,
        'leading_candidate' => null,
        'live_pricing_performed' => null,
        'next_actions' => null,
        'order_created' => null,
        'outcome' => null,
        'persistence_performed' => null,
        'producer_acceptance_performed' => null,
        'producer_selection_performed' => null,
        'producer_universe_evaluated' => null,
        'producer_universe_size' => null,
        'ranking_performed' => null,
        'readiness' => null,
        'recipe' => null,
        'review_required_count' => null,
        'schema_name' => null,
        'schema_version' => null,
        'specmatch_performed' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'availability_checked' => false,
        'best_capable_candidate' => true,
        'blocked_count' => false,
        'candidates' => false,
        'confirmed_capable_count' => false,
        'demand_basis' => false,
        'leading_candidate' => true,
        'live_pricing_performed' => false,
        'next_actions' => false,
        'order_created' => false,
        'outcome' => false,
        'persistence_performed' => false,
        'producer_acceptance_performed' => false,
        'producer_selection_performed' => false,
        'producer_universe_evaluated' => false,
        'producer_universe_size' => false,
        'ranking_performed' => false,
        'readiness' => false,
        'recipe' => false,
        'review_required_count' => false,
        'schema_name' => false,
        'schema_version' => false,
        'specmatch_performed' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'availability_checked' => 'availability_checked',
        'best_capable_candidate' => 'best_capable_candidate',
        'blocked_count' => 'blocked_count',
        'candidates' => 'candidates',
        'confirmed_capable_count' => 'confirmed_capable_count',
        'demand_basis' => 'demand_basis',
        'leading_candidate' => 'leading_candidate',
        'live_pricing_performed' => 'live_pricing_performed',
        'next_actions' => 'next_actions',
        'order_created' => 'order_created',
        'outcome' => 'outcome',
        'persistence_performed' => 'persistence_performed',
        'producer_acceptance_performed' => 'producer_acceptance_performed',
        'producer_selection_performed' => 'producer_selection_performed',
        'producer_universe_evaluated' => 'producer_universe_evaluated',
        'producer_universe_size' => 'producer_universe_size',
        'ranking_performed' => 'ranking_performed',
        'readiness' => 'readiness',
        'recipe' => 'recipe',
        'review_required_count' => 'review_required_count',
        'schema_name' => 'schema_name',
        'schema_version' => 'schema_version',
        'specmatch_performed' => 'specmatch_performed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'availability_checked' => 'setAvailabilityChecked',
        'best_capable_candidate' => 'setBestCapableCandidate',
        'blocked_count' => 'setBlockedCount',
        'candidates' => 'setCandidates',
        'confirmed_capable_count' => 'setConfirmedCapableCount',
        'demand_basis' => 'setDemandBasis',
        'leading_candidate' => 'setLeadingCandidate',
        'live_pricing_performed' => 'setLivePricingPerformed',
        'next_actions' => 'setNextActions',
        'order_created' => 'setOrderCreated',
        'outcome' => 'setOutcome',
        'persistence_performed' => 'setPersistencePerformed',
        'producer_acceptance_performed' => 'setProducerAcceptancePerformed',
        'producer_selection_performed' => 'setProducerSelectionPerformed',
        'producer_universe_evaluated' => 'setProducerUniverseEvaluated',
        'producer_universe_size' => 'setProducerUniverseSize',
        'ranking_performed' => 'setRankingPerformed',
        'readiness' => 'setReadiness',
        'recipe' => 'setRecipe',
        'review_required_count' => 'setReviewRequiredCount',
        'schema_name' => 'setSchemaName',
        'schema_version' => 'setSchemaVersion',
        'specmatch_performed' => 'setSpecmatchPerformed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'availability_checked' => 'getAvailabilityChecked',
        'best_capable_candidate' => 'getBestCapableCandidate',
        'blocked_count' => 'getBlockedCount',
        'candidates' => 'getCandidates',
        'confirmed_capable_count' => 'getConfirmedCapableCount',
        'demand_basis' => 'getDemandBasis',
        'leading_candidate' => 'getLeadingCandidate',
        'live_pricing_performed' => 'getLivePricingPerformed',
        'next_actions' => 'getNextActions',
        'order_created' => 'getOrderCreated',
        'outcome' => 'getOutcome',
        'persistence_performed' => 'getPersistencePerformed',
        'producer_acceptance_performed' => 'getProducerAcceptancePerformed',
        'producer_selection_performed' => 'getProducerSelectionPerformed',
        'producer_universe_evaluated' => 'getProducerUniverseEvaluated',
        'producer_universe_size' => 'getProducerUniverseSize',
        'ranking_performed' => 'getRankingPerformed',
        'readiness' => 'getReadiness',
        'recipe' => 'getRecipe',
        'review_required_count' => 'getReviewRequiredCount',
        'schema_name' => 'getSchemaName',
        'schema_version' => 'getSchemaVersion',
        'specmatch_performed' => 'getSpecmatchPerformed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AVAILABILITY_CHECKED_FALSE = 'false';
    public const DEMAND_BASIS_RECIPE = 'recipe';
    public const DEMAND_BASIS_GJS = 'gjs';
    public const LIVE_PRICING_PERFORMED_FALSE = 'false';
    public const ORDER_CREATED_FALSE = 'false';
    public const OUTCOME_CAPABLE_PRODUCER_FOUND = 'capable_producer_found';
    public const OUTCOME_REVIEW_REQUIRED = 'review_required';
    public const OUTCOME_NO_CAPABLE_PRODUCER = 'no_capable_producer';
    public const PERSISTENCE_PERFORMED_FALSE = 'false';
    public const PRODUCER_ACCEPTANCE_PERFORMED_FALSE = 'false';
    public const PRODUCER_SELECTION_PERFORMED_FALSE = 'false';
    public const PRODUCER_UNIVERSE_EVALUATED_TRUE = 'true';
    public const RANKING_PERFORMED_TRUE = 'true';
    public const SCHEMA_NAME_GNAWW_SPECMATCH_UNIVERSE_RESULT = 'gnaww.specmatch_universe_result';
    public const SCHEMA_VERSION__0_1 = '0.1';
    public const SPECMATCH_PERFORMED_TRUE = 'true';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAvailabilityCheckedAllowableValues()
    {
        return [
            self::AVAILABILITY_CHECKED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDemandBasisAllowableValues()
    {
        return [
            self::DEMAND_BASIS_RECIPE,
            self::DEMAND_BASIS_GJS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLivePricingPerformedAllowableValues()
    {
        return [
            self::LIVE_PRICING_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrderCreatedAllowableValues()
    {
        return [
            self::ORDER_CREATED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOutcomeAllowableValues()
    {
        return [
            self::OUTCOME_CAPABLE_PRODUCER_FOUND,
            self::OUTCOME_REVIEW_REQUIRED,
            self::OUTCOME_NO_CAPABLE_PRODUCER,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPersistencePerformedAllowableValues()
    {
        return [
            self::PERSISTENCE_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerAcceptancePerformedAllowableValues()
    {
        return [
            self::PRODUCER_ACCEPTANCE_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerSelectionPerformedAllowableValues()
    {
        return [
            self::PRODUCER_SELECTION_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerUniverseEvaluatedAllowableValues()
    {
        return [
            self::PRODUCER_UNIVERSE_EVALUATED_TRUE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRankingPerformedAllowableValues()
    {
        return [
            self::RANKING_PERFORMED_TRUE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaNameAllowableValues()
    {
        return [
            self::SCHEMA_NAME_GNAWW_SPECMATCH_UNIVERSE_RESULT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaVersionAllowableValues()
    {
        return [
            self::SCHEMA_VERSION__0_1,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSpecmatchPerformedAllowableValues()
    {
        return [
            self::SPECMATCH_PERFORMED_TRUE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('availability_checked', $data ?? [], false);
        $this->setIfExists('best_capable_candidate', $data ?? [], null);
        $this->setIfExists('blocked_count', $data ?? [], null);
        $this->setIfExists('candidates', $data ?? [], null);
        $this->setIfExists('confirmed_capable_count', $data ?? [], null);
        $this->setIfExists('demand_basis', $data ?? [], null);
        $this->setIfExists('leading_candidate', $data ?? [], null);
        $this->setIfExists('live_pricing_performed', $data ?? [], false);
        $this->setIfExists('next_actions', $data ?? [], null);
        $this->setIfExists('order_created', $data ?? [], false);
        $this->setIfExists('outcome', $data ?? [], null);
        $this->setIfExists('persistence_performed', $data ?? [], false);
        $this->setIfExists('producer_acceptance_performed', $data ?? [], false);
        $this->setIfExists('producer_selection_performed', $data ?? [], false);
        $this->setIfExists('producer_universe_evaluated', $data ?? [], true);
        $this->setIfExists('producer_universe_size', $data ?? [], null);
        $this->setIfExists('ranking_performed', $data ?? [], true);
        $this->setIfExists('readiness', $data ?? [], null);
        $this->setIfExists('recipe', $data ?? [], null);
        $this->setIfExists('review_required_count', $data ?? [], null);
        $this->setIfExists('schema_name', $data ?? [], 'gnaww.specmatch_universe_result');
        $this->setIfExists('schema_version', $data ?? [], '0.1');
        $this->setIfExists('specmatch_performed', $data ?? [], true);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAvailabilityCheckedAllowableValues();
        if (!is_null($this->container['availability_checked']) && !in_array($this->container['availability_checked'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'availability_checked', must be one of '%s'",
                $this->container['availability_checked'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['blocked_count'] === null) {
            $invalidProperties[] = "'blocked_count' can't be null";
        }
        if (($this->container['blocked_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'blocked_count', must be bigger than or equal to 0.";
        }

        if ($this->container['confirmed_capable_count'] === null) {
            $invalidProperties[] = "'confirmed_capable_count' can't be null";
        }
        if (($this->container['confirmed_capable_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'confirmed_capable_count', must be bigger than or equal to 0.";
        }

        if ($this->container['demand_basis'] === null) {
            $invalidProperties[] = "'demand_basis' can't be null";
        }
        $allowedValues = $this->getDemandBasisAllowableValues();
        if (!is_null($this->container['demand_basis']) && !in_array($this->container['demand_basis'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'demand_basis', must be one of '%s'",
                $this->container['demand_basis'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLivePricingPerformedAllowableValues();
        if (!is_null($this->container['live_pricing_performed']) && !in_array($this->container['live_pricing_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'live_pricing_performed', must be one of '%s'",
                $this->container['live_pricing_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOrderCreatedAllowableValues();
        if (!is_null($this->container['order_created']) && !in_array($this->container['order_created'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'order_created', must be one of '%s'",
                $this->container['order_created'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['outcome'] === null) {
            $invalidProperties[] = "'outcome' can't be null";
        }
        $allowedValues = $this->getOutcomeAllowableValues();
        if (!is_null($this->container['outcome']) && !in_array($this->container['outcome'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'outcome', must be one of '%s'",
                $this->container['outcome'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPersistencePerformedAllowableValues();
        if (!is_null($this->container['persistence_performed']) && !in_array($this->container['persistence_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'persistence_performed', must be one of '%s'",
                $this->container['persistence_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerAcceptancePerformedAllowableValues();
        if (!is_null($this->container['producer_acceptance_performed']) && !in_array($this->container['producer_acceptance_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_acceptance_performed', must be one of '%s'",
                $this->container['producer_acceptance_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!is_null($this->container['producer_selection_performed']) && !in_array($this->container['producer_selection_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                $this->container['producer_selection_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerUniverseEvaluatedAllowableValues();
        if (!is_null($this->container['producer_universe_evaluated']) && !in_array($this->container['producer_universe_evaluated'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_universe_evaluated', must be one of '%s'",
                $this->container['producer_universe_evaluated'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['producer_universe_size'] === null) {
            $invalidProperties[] = "'producer_universe_size' can't be null";
        }
        if (($this->container['producer_universe_size'] < 0)) {
            $invalidProperties[] = "invalid value for 'producer_universe_size', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getRankingPerformedAllowableValues();
        if (!is_null($this->container['ranking_performed']) && !in_array($this->container['ranking_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'ranking_performed', must be one of '%s'",
                $this->container['ranking_performed'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['readiness'] === null) {
            $invalidProperties[] = "'readiness' can't be null";
        }
        if ($this->container['recipe'] === null) {
            $invalidProperties[] = "'recipe' can't be null";
        }
        if ($this->container['review_required_count'] === null) {
            $invalidProperties[] = "'review_required_count' can't be null";
        }
        if (($this->container['review_required_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'review_required_count', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!is_null($this->container['schema_name']) && !in_array($this->container['schema_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_name', must be one of '%s'",
                $this->container['schema_name'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSchemaVersionAllowableValues();
        if (!is_null($this->container['schema_version']) && !in_array($this->container['schema_version'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_version', must be one of '%s'",
                $this->container['schema_version'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!is_null($this->container['specmatch_performed']) && !in_array($this->container['specmatch_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                $this->container['specmatch_performed'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets availability_checked
     *
     * @return bool|null
     */
    public function getAvailabilityChecked()
    {
        return $this->container['availability_checked'];
    }

    /**
     * Sets availability_checked
     *
     * @param bool|null $availability_checked availability_checked
     *
     * @return self
     */
    public function setAvailabilityChecked($availability_checked)
    {
        if (is_null($availability_checked)) {
            throw new \InvalidArgumentException('non-nullable availability_checked cannot be null');
        }
        $allowedValues = $this->getAvailabilityCheckedAllowableValues();
        if (!in_array($availability_checked, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'availability_checked', must be one of '%s'",
                    $availability_checked,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['availability_checked'] = $availability_checked;

        return $this;
    }

    /**
     * Gets best_capable_candidate
     *
     * @return \Jawwws\Gnaww\Model\PublicProducerUniverseCandidate|null
     */
    public function getBestCapableCandidate()
    {
        return $this->container['best_capable_candidate'];
    }

    /**
     * Sets best_capable_candidate
     *
     * @param \Jawwws\Gnaww\Model\PublicProducerUniverseCandidate|null $best_capable_candidate best_capable_candidate
     *
     * @return self
     */
    public function setBestCapableCandidate($best_capable_candidate)
    {
        if (is_null($best_capable_candidate)) {
            array_push($this->openAPINullablesSetToNull, 'best_capable_candidate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('best_capable_candidate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['best_capable_candidate'] = $best_capable_candidate;

        return $this;
    }

    /**
     * Gets blocked_count
     *
     * @return int
     */
    public function getBlockedCount()
    {
        return $this->container['blocked_count'];
    }

    /**
     * Sets blocked_count
     *
     * @param int $blocked_count blocked_count
     *
     * @return self
     */
    public function setBlockedCount($blocked_count)
    {
        if (is_null($blocked_count)) {
            throw new \InvalidArgumentException('non-nullable blocked_count cannot be null');
        }

        if (($blocked_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $blocked_count when calling MatchPrintDemandUniverseResponse., must be bigger than or equal to 0.');
        }

        $this->container['blocked_count'] = $blocked_count;

        return $this;
    }

    /**
     * Gets candidates
     *
     * @return \Jawwws\Gnaww\Model\PublicProducerUniverseCandidate[]|null
     */
    public function getCandidates()
    {
        return $this->container['candidates'];
    }

    /**
     * Sets candidates
     *
     * @param \Jawwws\Gnaww\Model\PublicProducerUniverseCandidate[]|null $candidates candidates
     *
     * @return self
     */
    public function setCandidates($candidates)
    {
        if (is_null($candidates)) {
            throw new \InvalidArgumentException('non-nullable candidates cannot be null');
        }
        $this->container['candidates'] = $candidates;

        return $this;
    }

    /**
     * Gets confirmed_capable_count
     *
     * @return int
     */
    public function getConfirmedCapableCount()
    {
        return $this->container['confirmed_capable_count'];
    }

    /**
     * Sets confirmed_capable_count
     *
     * @param int $confirmed_capable_count confirmed_capable_count
     *
     * @return self
     */
    public function setConfirmedCapableCount($confirmed_capable_count)
    {
        if (is_null($confirmed_capable_count)) {
            throw new \InvalidArgumentException('non-nullable confirmed_capable_count cannot be null');
        }

        if (($confirmed_capable_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $confirmed_capable_count when calling MatchPrintDemandUniverseResponse., must be bigger than or equal to 0.');
        }

        $this->container['confirmed_capable_count'] = $confirmed_capable_count;

        return $this;
    }

    /**
     * Gets demand_basis
     *
     * @return string
     */
    public function getDemandBasis()
    {
        return $this->container['demand_basis'];
    }

    /**
     * Sets demand_basis
     *
     * @param string $demand_basis demand_basis
     *
     * @return self
     */
    public function setDemandBasis($demand_basis)
    {
        if (is_null($demand_basis)) {
            throw new \InvalidArgumentException('non-nullable demand_basis cannot be null');
        }
        $allowedValues = $this->getDemandBasisAllowableValues();
        if (!in_array($demand_basis, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'demand_basis', must be one of '%s'",
                    $demand_basis,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['demand_basis'] = $demand_basis;

        return $this;
    }

    /**
     * Gets leading_candidate
     *
     * @return \Jawwws\Gnaww\Model\PublicProducerUniverseCandidate|null
     */
    public function getLeadingCandidate()
    {
        return $this->container['leading_candidate'];
    }

    /**
     * Sets leading_candidate
     *
     * @param \Jawwws\Gnaww\Model\PublicProducerUniverseCandidate|null $leading_candidate leading_candidate
     *
     * @return self
     */
    public function setLeadingCandidate($leading_candidate)
    {
        if (is_null($leading_candidate)) {
            array_push($this->openAPINullablesSetToNull, 'leading_candidate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('leading_candidate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['leading_candidate'] = $leading_candidate;

        return $this;
    }

    /**
     * Gets live_pricing_performed
     *
     * @return bool|null
     */
    public function getLivePricingPerformed()
    {
        return $this->container['live_pricing_performed'];
    }

    /**
     * Sets live_pricing_performed
     *
     * @param bool|null $live_pricing_performed live_pricing_performed
     *
     * @return self
     */
    public function setLivePricingPerformed($live_pricing_performed)
    {
        if (is_null($live_pricing_performed)) {
            throw new \InvalidArgumentException('non-nullable live_pricing_performed cannot be null');
        }
        $allowedValues = $this->getLivePricingPerformedAllowableValues();
        if (!in_array($live_pricing_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'live_pricing_performed', must be one of '%s'",
                    $live_pricing_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['live_pricing_performed'] = $live_pricing_performed;

        return $this;
    }

    /**
     * Gets next_actions
     *
     * @return string[]|null
     */
    public function getNextActions()
    {
        return $this->container['next_actions'];
    }

    /**
     * Sets next_actions
     *
     * @param string[]|null $next_actions next_actions
     *
     * @return self
     */
    public function setNextActions($next_actions)
    {
        if (is_null($next_actions)) {
            throw new \InvalidArgumentException('non-nullable next_actions cannot be null');
        }
        $this->container['next_actions'] = $next_actions;

        return $this;
    }

    /**
     * Gets order_created
     *
     * @return bool|null
     */
    public function getOrderCreated()
    {
        return $this->container['order_created'];
    }

    /**
     * Sets order_created
     *
     * @param bool|null $order_created order_created
     *
     * @return self
     */
    public function setOrderCreated($order_created)
    {
        if (is_null($order_created)) {
            throw new \InvalidArgumentException('non-nullable order_created cannot be null');
        }
        $allowedValues = $this->getOrderCreatedAllowableValues();
        if (!in_array($order_created, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'order_created', must be one of '%s'",
                    $order_created,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['order_created'] = $order_created;

        return $this;
    }

    /**
     * Gets outcome
     *
     * @return string
     */
    public function getOutcome()
    {
        return $this->container['outcome'];
    }

    /**
     * Sets outcome
     *
     * @param string $outcome outcome
     *
     * @return self
     */
    public function setOutcome($outcome)
    {
        if (is_null($outcome)) {
            throw new \InvalidArgumentException('non-nullable outcome cannot be null');
        }
        $allowedValues = $this->getOutcomeAllowableValues();
        if (!in_array($outcome, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'outcome', must be one of '%s'",
                    $outcome,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['outcome'] = $outcome;

        return $this;
    }

    /**
     * Gets persistence_performed
     *
     * @return bool|null
     */
    public function getPersistencePerformed()
    {
        return $this->container['persistence_performed'];
    }

    /**
     * Sets persistence_performed
     *
     * @param bool|null $persistence_performed persistence_performed
     *
     * @return self
     */
    public function setPersistencePerformed($persistence_performed)
    {
        if (is_null($persistence_performed)) {
            throw new \InvalidArgumentException('non-nullable persistence_performed cannot be null');
        }
        $allowedValues = $this->getPersistencePerformedAllowableValues();
        if (!in_array($persistence_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'persistence_performed', must be one of '%s'",
                    $persistence_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['persistence_performed'] = $persistence_performed;

        return $this;
    }

    /**
     * Gets producer_acceptance_performed
     *
     * @return bool|null
     */
    public function getProducerAcceptancePerformed()
    {
        return $this->container['producer_acceptance_performed'];
    }

    /**
     * Sets producer_acceptance_performed
     *
     * @param bool|null $producer_acceptance_performed producer_acceptance_performed
     *
     * @return self
     */
    public function setProducerAcceptancePerformed($producer_acceptance_performed)
    {
        if (is_null($producer_acceptance_performed)) {
            throw new \InvalidArgumentException('non-nullable producer_acceptance_performed cannot be null');
        }
        $allowedValues = $this->getProducerAcceptancePerformedAllowableValues();
        if (!in_array($producer_acceptance_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_acceptance_performed', must be one of '%s'",
                    $producer_acceptance_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_acceptance_performed'] = $producer_acceptance_performed;

        return $this;
    }

    /**
     * Gets producer_selection_performed
     *
     * @return bool|null
     */
    public function getProducerSelectionPerformed()
    {
        return $this->container['producer_selection_performed'];
    }

    /**
     * Sets producer_selection_performed
     *
     * @param bool|null $producer_selection_performed producer_selection_performed
     *
     * @return self
     */
    public function setProducerSelectionPerformed($producer_selection_performed)
    {
        if (is_null($producer_selection_performed)) {
            throw new \InvalidArgumentException('non-nullable producer_selection_performed cannot be null');
        }
        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!in_array($producer_selection_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                    $producer_selection_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_selection_performed'] = $producer_selection_performed;

        return $this;
    }

    /**
     * Gets producer_universe_evaluated
     *
     * @return bool|null
     */
    public function getProducerUniverseEvaluated()
    {
        return $this->container['producer_universe_evaluated'];
    }

    /**
     * Sets producer_universe_evaluated
     *
     * @param bool|null $producer_universe_evaluated producer_universe_evaluated
     *
     * @return self
     */
    public function setProducerUniverseEvaluated($producer_universe_evaluated)
    {
        if (is_null($producer_universe_evaluated)) {
            throw new \InvalidArgumentException('non-nullable producer_universe_evaluated cannot be null');
        }
        $allowedValues = $this->getProducerUniverseEvaluatedAllowableValues();
        if (!in_array($producer_universe_evaluated, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_universe_evaluated', must be one of '%s'",
                    $producer_universe_evaluated,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_universe_evaluated'] = $producer_universe_evaluated;

        return $this;
    }

    /**
     * Gets producer_universe_size
     *
     * @return int
     */
    public function getProducerUniverseSize()
    {
        return $this->container['producer_universe_size'];
    }

    /**
     * Sets producer_universe_size
     *
     * @param int $producer_universe_size producer_universe_size
     *
     * @return self
     */
    public function setProducerUniverseSize($producer_universe_size)
    {
        if (is_null($producer_universe_size)) {
            throw new \InvalidArgumentException('non-nullable producer_universe_size cannot be null');
        }

        if (($producer_universe_size < 0)) {
            throw new \InvalidArgumentException('invalid value for $producer_universe_size when calling MatchPrintDemandUniverseResponse., must be bigger than or equal to 0.');
        }

        $this->container['producer_universe_size'] = $producer_universe_size;

        return $this;
    }

    /**
     * Gets ranking_performed
     *
     * @return bool|null
     */
    public function getRankingPerformed()
    {
        return $this->container['ranking_performed'];
    }

    /**
     * Sets ranking_performed
     *
     * @param bool|null $ranking_performed ranking_performed
     *
     * @return self
     */
    public function setRankingPerformed($ranking_performed)
    {
        if (is_null($ranking_performed)) {
            throw new \InvalidArgumentException('non-nullable ranking_performed cannot be null');
        }
        $allowedValues = $this->getRankingPerformedAllowableValues();
        if (!in_array($ranking_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'ranking_performed', must be one of '%s'",
                    $ranking_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ranking_performed'] = $ranking_performed;

        return $this;
    }

    /**
     * Gets readiness
     *
     * @return \Jawwws\Gnaww\Model\PublicSpecMatchReadiness
     */
    public function getReadiness()
    {
        return $this->container['readiness'];
    }

    /**
     * Sets readiness
     *
     * @param \Jawwws\Gnaww\Model\PublicSpecMatchReadiness $readiness readiness
     *
     * @return self
     */
    public function setReadiness($readiness)
    {
        if (is_null($readiness)) {
            throw new \InvalidArgumentException('non-nullable readiness cannot be null');
        }
        $this->container['readiness'] = $readiness;

        return $this;
    }

    /**
     * Gets recipe
     *
     * @return \Jawwws\Gnaww\Model\PublicRecipeState
     */
    public function getRecipe()
    {
        return $this->container['recipe'];
    }

    /**
     * Sets recipe
     *
     * @param \Jawwws\Gnaww\Model\PublicRecipeState $recipe recipe
     *
     * @return self
     */
    public function setRecipe($recipe)
    {
        if (is_null($recipe)) {
            throw new \InvalidArgumentException('non-nullable recipe cannot be null');
        }
        $this->container['recipe'] = $recipe;

        return $this;
    }

    /**
     * Gets review_required_count
     *
     * @return int
     */
    public function getReviewRequiredCount()
    {
        return $this->container['review_required_count'];
    }

    /**
     * Sets review_required_count
     *
     * @param int $review_required_count review_required_count
     *
     * @return self
     */
    public function setReviewRequiredCount($review_required_count)
    {
        if (is_null($review_required_count)) {
            throw new \InvalidArgumentException('non-nullable review_required_count cannot be null');
        }

        if (($review_required_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $review_required_count when calling MatchPrintDemandUniverseResponse., must be bigger than or equal to 0.');
        }

        $this->container['review_required_count'] = $review_required_count;

        return $this;
    }

    /**
     * Gets schema_name
     *
     * @return string|null
     */
    public function getSchemaName()
    {
        return $this->container['schema_name'];
    }

    /**
     * Sets schema_name
     *
     * @param string|null $schema_name schema_name
     *
     * @return self
     */
    public function setSchemaName($schema_name)
    {
        if (is_null($schema_name)) {
            throw new \InvalidArgumentException('non-nullable schema_name cannot be null');
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!in_array($schema_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_name', must be one of '%s'",
                    $schema_name,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_name'] = $schema_name;

        return $this;
    }

    /**
     * Gets schema_version
     *
     * @return string|null
     */
    public function getSchemaVersion()
    {
        return $this->container['schema_version'];
    }

    /**
     * Sets schema_version
     *
     * @param string|null $schema_version schema_version
     *
     * @return self
     */
    public function setSchemaVersion($schema_version)
    {
        if (is_null($schema_version)) {
            throw new \InvalidArgumentException('non-nullable schema_version cannot be null');
        }
        $allowedValues = $this->getSchemaVersionAllowableValues();
        if (!in_array($schema_version, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_version', must be one of '%s'",
                    $schema_version,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_version'] = $schema_version;

        return $this;
    }

    /**
     * Gets specmatch_performed
     *
     * @return bool|null
     */
    public function getSpecmatchPerformed()
    {
        return $this->container['specmatch_performed'];
    }

    /**
     * Sets specmatch_performed
     *
     * @param bool|null $specmatch_performed specmatch_performed
     *
     * @return self
     */
    public function setSpecmatchPerformed($specmatch_performed)
    {
        if (is_null($specmatch_performed)) {
            throw new \InvalidArgumentException('non-nullable specmatch_performed cannot be null');
        }
        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!in_array($specmatch_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                    $specmatch_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['specmatch_performed'] = $specmatch_performed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
