<?php
/**
 * MatchRecipeResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * MatchRecipeResponse Class Doc Comment
 *
 * @category Class
 * @description Public deterministic capability-fit result for one persisted Recipe.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MatchRecipeResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MatchRecipeResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'availability_checked' => 'bool',
        'demand_basis' => 'string',
        'live_pricing_performed' => 'bool',
        'match' => '\Jawwws\Gnaww\Model\SpecMatchResult',
        'next_actions' => 'string[]',
        'order_created' => 'bool',
        'persistence_performed' => 'bool',
        'producer_acceptance_performed' => 'bool',
        'producer_selection_performed' => 'bool',
        'readiness' => '\Jawwws\Gnaww\Model\PublicSpecMatchReadiness',
        'recipe' => '\Jawwws\Gnaww\Model\ResolvedRecipeMatchState',
        'schema_name' => 'string',
        'schema_version' => 'string',
        'specmatch_performed' => 'bool',
        'status' => 'string',
        'target' => '\Jawwws\Gnaww\Model\PublicMatchTargetState'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'availability_checked' => null,
        'demand_basis' => null,
        'live_pricing_performed' => null,
        'match' => null,
        'next_actions' => null,
        'order_created' => null,
        'persistence_performed' => null,
        'producer_acceptance_performed' => null,
        'producer_selection_performed' => null,
        'readiness' => null,
        'recipe' => null,
        'schema_name' => null,
        'schema_version' => null,
        'specmatch_performed' => null,
        'status' => null,
        'target' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'availability_checked' => false,
        'demand_basis' => false,
        'live_pricing_performed' => false,
        'match' => false,
        'next_actions' => false,
        'order_created' => false,
        'persistence_performed' => false,
        'producer_acceptance_performed' => false,
        'producer_selection_performed' => false,
        'readiness' => false,
        'recipe' => false,
        'schema_name' => false,
        'schema_version' => false,
        'specmatch_performed' => false,
        'status' => false,
        'target' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'availability_checked' => 'availability_checked',
        'demand_basis' => 'demand_basis',
        'live_pricing_performed' => 'live_pricing_performed',
        'match' => 'match',
        'next_actions' => 'next_actions',
        'order_created' => 'order_created',
        'persistence_performed' => 'persistence_performed',
        'producer_acceptance_performed' => 'producer_acceptance_performed',
        'producer_selection_performed' => 'producer_selection_performed',
        'readiness' => 'readiness',
        'recipe' => 'recipe',
        'schema_name' => 'schema_name',
        'schema_version' => 'schema_version',
        'specmatch_performed' => 'specmatch_performed',
        'status' => 'status',
        'target' => 'target'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'availability_checked' => 'setAvailabilityChecked',
        'demand_basis' => 'setDemandBasis',
        'live_pricing_performed' => 'setLivePricingPerformed',
        'match' => 'setMatch',
        'next_actions' => 'setNextActions',
        'order_created' => 'setOrderCreated',
        'persistence_performed' => 'setPersistencePerformed',
        'producer_acceptance_performed' => 'setProducerAcceptancePerformed',
        'producer_selection_performed' => 'setProducerSelectionPerformed',
        'readiness' => 'setReadiness',
        'recipe' => 'setRecipe',
        'schema_name' => 'setSchemaName',
        'schema_version' => 'setSchemaVersion',
        'specmatch_performed' => 'setSpecmatchPerformed',
        'status' => 'setStatus',
        'target' => 'setTarget'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'availability_checked' => 'getAvailabilityChecked',
        'demand_basis' => 'getDemandBasis',
        'live_pricing_performed' => 'getLivePricingPerformed',
        'match' => 'getMatch',
        'next_actions' => 'getNextActions',
        'order_created' => 'getOrderCreated',
        'persistence_performed' => 'getPersistencePerformed',
        'producer_acceptance_performed' => 'getProducerAcceptancePerformed',
        'producer_selection_performed' => 'getProducerSelectionPerformed',
        'readiness' => 'getReadiness',
        'recipe' => 'getRecipe',
        'schema_name' => 'getSchemaName',
        'schema_version' => 'getSchemaVersion',
        'specmatch_performed' => 'getSpecmatchPerformed',
        'status' => 'getStatus',
        'target' => 'getTarget'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AVAILABILITY_CHECKED_FALSE = 'false';
    public const DEMAND_BASIS_RECIPE = 'recipe';
    public const LIVE_PRICING_PERFORMED_FALSE = 'false';
    public const ORDER_CREATED_FALSE = 'false';
    public const PERSISTENCE_PERFORMED_FALSE = 'false';
    public const PRODUCER_ACCEPTANCE_PERFORMED_FALSE = 'false';
    public const PRODUCER_SELECTION_PERFORMED_FALSE = 'false';
    public const SCHEMA_NAME_GNAWW_RECIPE_SPECMATCH_RESULT = 'gnaww.recipe_specmatch_result';
    public const SCHEMA_VERSION__0_1 = '0.1';
    public const SPECMATCH_PERFORMED_TRUE = 'true';
    public const STATUS_MATCHED = 'matched';
    public const STATUS_MATCHED_WITH_WARNINGS = 'matched_with_warnings';
    public const STATUS_NEEDS_REVIEW = 'needs_review';
    public const STATUS_BLOCKED = 'blocked';
    public const STATUS_FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAvailabilityCheckedAllowableValues()
    {
        return [
            self::AVAILABILITY_CHECKED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDemandBasisAllowableValues()
    {
        return [
            self::DEMAND_BASIS_RECIPE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLivePricingPerformedAllowableValues()
    {
        return [
            self::LIVE_PRICING_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrderCreatedAllowableValues()
    {
        return [
            self::ORDER_CREATED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPersistencePerformedAllowableValues()
    {
        return [
            self::PERSISTENCE_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerAcceptancePerformedAllowableValues()
    {
        return [
            self::PRODUCER_ACCEPTANCE_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerSelectionPerformedAllowableValues()
    {
        return [
            self::PRODUCER_SELECTION_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaNameAllowableValues()
    {
        return [
            self::SCHEMA_NAME_GNAWW_RECIPE_SPECMATCH_RESULT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaVersionAllowableValues()
    {
        return [
            self::SCHEMA_VERSION__0_1,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSpecmatchPerformedAllowableValues()
    {
        return [
            self::SPECMATCH_PERFORMED_TRUE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_MATCHED,
            self::STATUS_MATCHED_WITH_WARNINGS,
            self::STATUS_NEEDS_REVIEW,
            self::STATUS_BLOCKED,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('availability_checked', $data ?? [], false);
        $this->setIfExists('demand_basis', $data ?? [], 'recipe');
        $this->setIfExists('live_pricing_performed', $data ?? [], false);
        $this->setIfExists('match', $data ?? [], null);
        $this->setIfExists('next_actions', $data ?? [], null);
        $this->setIfExists('order_created', $data ?? [], false);
        $this->setIfExists('persistence_performed', $data ?? [], false);
        $this->setIfExists('producer_acceptance_performed', $data ?? [], false);
        $this->setIfExists('producer_selection_performed', $data ?? [], false);
        $this->setIfExists('readiness', $data ?? [], null);
        $this->setIfExists('recipe', $data ?? [], null);
        $this->setIfExists('schema_name', $data ?? [], 'gnaww.recipe_specmatch_result');
        $this->setIfExists('schema_version', $data ?? [], '0.1');
        $this->setIfExists('specmatch_performed', $data ?? [], true);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('target', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAvailabilityCheckedAllowableValues();
        if (!is_null($this->container['availability_checked']) && !in_array($this->container['availability_checked'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'availability_checked', must be one of '%s'",
                $this->container['availability_checked'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDemandBasisAllowableValues();
        if (!is_null($this->container['demand_basis']) && !in_array($this->container['demand_basis'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'demand_basis', must be one of '%s'",
                $this->container['demand_basis'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLivePricingPerformedAllowableValues();
        if (!is_null($this->container['live_pricing_performed']) && !in_array($this->container['live_pricing_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'live_pricing_performed', must be one of '%s'",
                $this->container['live_pricing_performed'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['match'] === null) {
            $invalidProperties[] = "'match' can't be null";
        }
        $allowedValues = $this->getOrderCreatedAllowableValues();
        if (!is_null($this->container['order_created']) && !in_array($this->container['order_created'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'order_created', must be one of '%s'",
                $this->container['order_created'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPersistencePerformedAllowableValues();
        if (!is_null($this->container['persistence_performed']) && !in_array($this->container['persistence_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'persistence_performed', must be one of '%s'",
                $this->container['persistence_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerAcceptancePerformedAllowableValues();
        if (!is_null($this->container['producer_acceptance_performed']) && !in_array($this->container['producer_acceptance_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_acceptance_performed', must be one of '%s'",
                $this->container['producer_acceptance_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!is_null($this->container['producer_selection_performed']) && !in_array($this->container['producer_selection_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                $this->container['producer_selection_performed'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['readiness'] === null) {
            $invalidProperties[] = "'readiness' can't be null";
        }
        if ($this->container['recipe'] === null) {
            $invalidProperties[] = "'recipe' can't be null";
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!is_null($this->container['schema_name']) && !in_array($this->container['schema_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_name', must be one of '%s'",
                $this->container['schema_name'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSchemaVersionAllowableValues();
        if (!is_null($this->container['schema_version']) && !in_array($this->container['schema_version'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_version', must be one of '%s'",
                $this->container['schema_version'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!is_null($this->container['specmatch_performed']) && !in_array($this->container['specmatch_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                $this->container['specmatch_performed'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['target'] === null) {
            $invalidProperties[] = "'target' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets availability_checked
     *
     * @return bool|null
     */
    public function getAvailabilityChecked()
    {
        return $this->container['availability_checked'];
    }

    /**
     * Sets availability_checked
     *
     * @param bool|null $availability_checked availability_checked
     *
     * @return self
     */
    public function setAvailabilityChecked($availability_checked)
    {
        if (is_null($availability_checked)) {
            throw new \InvalidArgumentException('non-nullable availability_checked cannot be null');
        }
        $allowedValues = $this->getAvailabilityCheckedAllowableValues();
        if (!in_array($availability_checked, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'availability_checked', must be one of '%s'",
                    $availability_checked,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['availability_checked'] = $availability_checked;

        return $this;
    }

    /**
     * Gets demand_basis
     *
     * @return string|null
     */
    public function getDemandBasis()
    {
        return $this->container['demand_basis'];
    }

    /**
     * Sets demand_basis
     *
     * @param string|null $demand_basis demand_basis
     *
     * @return self
     */
    public function setDemandBasis($demand_basis)
    {
        if (is_null($demand_basis)) {
            throw new \InvalidArgumentException('non-nullable demand_basis cannot be null');
        }
        $allowedValues = $this->getDemandBasisAllowableValues();
        if (!in_array($demand_basis, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'demand_basis', must be one of '%s'",
                    $demand_basis,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['demand_basis'] = $demand_basis;

        return $this;
    }

    /**
     * Gets live_pricing_performed
     *
     * @return bool|null
     */
    public function getLivePricingPerformed()
    {
        return $this->container['live_pricing_performed'];
    }

    /**
     * Sets live_pricing_performed
     *
     * @param bool|null $live_pricing_performed live_pricing_performed
     *
     * @return self
     */
    public function setLivePricingPerformed($live_pricing_performed)
    {
        if (is_null($live_pricing_performed)) {
            throw new \InvalidArgumentException('non-nullable live_pricing_performed cannot be null');
        }
        $allowedValues = $this->getLivePricingPerformedAllowableValues();
        if (!in_array($live_pricing_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'live_pricing_performed', must be one of '%s'",
                    $live_pricing_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['live_pricing_performed'] = $live_pricing_performed;

        return $this;
    }

    /**
     * Gets match
     *
     * @return \Jawwws\Gnaww\Model\SpecMatchResult
     */
    public function getMatch()
    {
        return $this->container['match'];
    }

    /**
     * Sets match
     *
     * @param \Jawwws\Gnaww\Model\SpecMatchResult $match match
     *
     * @return self
     */
    public function setMatch($match)
    {
        if (is_null($match)) {
            throw new \InvalidArgumentException('non-nullable match cannot be null');
        }
        $this->container['match'] = $match;

        return $this;
    }

    /**
     * Gets next_actions
     *
     * @return string[]|null
     */
    public function getNextActions()
    {
        return $this->container['next_actions'];
    }

    /**
     * Sets next_actions
     *
     * @param string[]|null $next_actions next_actions
     *
     * @return self
     */
    public function setNextActions($next_actions)
    {
        if (is_null($next_actions)) {
            throw new \InvalidArgumentException('non-nullable next_actions cannot be null');
        }
        $this->container['next_actions'] = $next_actions;

        return $this;
    }

    /**
     * Gets order_created
     *
     * @return bool|null
     */
    public function getOrderCreated()
    {
        return $this->container['order_created'];
    }

    /**
     * Sets order_created
     *
     * @param bool|null $order_created order_created
     *
     * @return self
     */
    public function setOrderCreated($order_created)
    {
        if (is_null($order_created)) {
            throw new \InvalidArgumentException('non-nullable order_created cannot be null');
        }
        $allowedValues = $this->getOrderCreatedAllowableValues();
        if (!in_array($order_created, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'order_created', must be one of '%s'",
                    $order_created,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['order_created'] = $order_created;

        return $this;
    }

    /**
     * Gets persistence_performed
     *
     * @return bool|null
     */
    public function getPersistencePerformed()
    {
        return $this->container['persistence_performed'];
    }

    /**
     * Sets persistence_performed
     *
     * @param bool|null $persistence_performed persistence_performed
     *
     * @return self
     */
    public function setPersistencePerformed($persistence_performed)
    {
        if (is_null($persistence_performed)) {
            throw new \InvalidArgumentException('non-nullable persistence_performed cannot be null');
        }
        $allowedValues = $this->getPersistencePerformedAllowableValues();
        if (!in_array($persistence_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'persistence_performed', must be one of '%s'",
                    $persistence_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['persistence_performed'] = $persistence_performed;

        return $this;
    }

    /**
     * Gets producer_acceptance_performed
     *
     * @return bool|null
     */
    public function getProducerAcceptancePerformed()
    {
        return $this->container['producer_acceptance_performed'];
    }

    /**
     * Sets producer_acceptance_performed
     *
     * @param bool|null $producer_acceptance_performed producer_acceptance_performed
     *
     * @return self
     */
    public function setProducerAcceptancePerformed($producer_acceptance_performed)
    {
        if (is_null($producer_acceptance_performed)) {
            throw new \InvalidArgumentException('non-nullable producer_acceptance_performed cannot be null');
        }
        $allowedValues = $this->getProducerAcceptancePerformedAllowableValues();
        if (!in_array($producer_acceptance_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_acceptance_performed', must be one of '%s'",
                    $producer_acceptance_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_acceptance_performed'] = $producer_acceptance_performed;

        return $this;
    }

    /**
     * Gets producer_selection_performed
     *
     * @return bool|null
     */
    public function getProducerSelectionPerformed()
    {
        return $this->container['producer_selection_performed'];
    }

    /**
     * Sets producer_selection_performed
     *
     * @param bool|null $producer_selection_performed producer_selection_performed
     *
     * @return self
     */
    public function setProducerSelectionPerformed($producer_selection_performed)
    {
        if (is_null($producer_selection_performed)) {
            throw new \InvalidArgumentException('non-nullable producer_selection_performed cannot be null');
        }
        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!in_array($producer_selection_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                    $producer_selection_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_selection_performed'] = $producer_selection_performed;

        return $this;
    }

    /**
     * Gets readiness
     *
     * @return \Jawwws\Gnaww\Model\PublicSpecMatchReadiness
     */
    public function getReadiness()
    {
        return $this->container['readiness'];
    }

    /**
     * Sets readiness
     *
     * @param \Jawwws\Gnaww\Model\PublicSpecMatchReadiness $readiness readiness
     *
     * @return self
     */
    public function setReadiness($readiness)
    {
        if (is_null($readiness)) {
            throw new \InvalidArgumentException('non-nullable readiness cannot be null');
        }
        $this->container['readiness'] = $readiness;

        return $this;
    }

    /**
     * Gets recipe
     *
     * @return \Jawwws\Gnaww\Model\ResolvedRecipeMatchState
     */
    public function getRecipe()
    {
        return $this->container['recipe'];
    }

    /**
     * Sets recipe
     *
     * @param \Jawwws\Gnaww\Model\ResolvedRecipeMatchState $recipe recipe
     *
     * @return self
     */
    public function setRecipe($recipe)
    {
        if (is_null($recipe)) {
            throw new \InvalidArgumentException('non-nullable recipe cannot be null');
        }
        $this->container['recipe'] = $recipe;

        return $this;
    }

    /**
     * Gets schema_name
     *
     * @return string|null
     */
    public function getSchemaName()
    {
        return $this->container['schema_name'];
    }

    /**
     * Sets schema_name
     *
     * @param string|null $schema_name schema_name
     *
     * @return self
     */
    public function setSchemaName($schema_name)
    {
        if (is_null($schema_name)) {
            throw new \InvalidArgumentException('non-nullable schema_name cannot be null');
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!in_array($schema_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_name', must be one of '%s'",
                    $schema_name,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_name'] = $schema_name;

        return $this;
    }

    /**
     * Gets schema_version
     *
     * @return string|null
     */
    public function getSchemaVersion()
    {
        return $this->container['schema_version'];
    }

    /**
     * Sets schema_version
     *
     * @param string|null $schema_version schema_version
     *
     * @return self
     */
    public function setSchemaVersion($schema_version)
    {
        if (is_null($schema_version)) {
            throw new \InvalidArgumentException('non-nullable schema_version cannot be null');
        }
        $allowedValues = $this->getSchemaVersionAllowableValues();
        if (!in_array($schema_version, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_version', must be one of '%s'",
                    $schema_version,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_version'] = $schema_version;

        return $this;
    }

    /**
     * Gets specmatch_performed
     *
     * @return bool|null
     */
    public function getSpecmatchPerformed()
    {
        return $this->container['specmatch_performed'];
    }

    /**
     * Sets specmatch_performed
     *
     * @param bool|null $specmatch_performed specmatch_performed
     *
     * @return self
     */
    public function setSpecmatchPerformed($specmatch_performed)
    {
        if (is_null($specmatch_performed)) {
            throw new \InvalidArgumentException('non-nullable specmatch_performed cannot be null');
        }
        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!in_array($specmatch_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                    $specmatch_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['specmatch_performed'] = $specmatch_performed;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets target
     *
     * @return \Jawwws\Gnaww\Model\PublicMatchTargetState
     */
    public function getTarget()
    {
        return $this->container['target'];
    }

    /**
     * Sets target
     *
     * @param \Jawwws\Gnaww\Model\PublicMatchTargetState $target target
     *
     * @return self
     */
    public function setTarget($target)
    {
        if (is_null($target)) {
            throw new \InvalidArgumentException('non-nullable target cannot be null');
        }
        $this->container['target'] = $target;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
