<?php
/**
 * PrintSpec
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * PrintSpec Class Doc Comment
 *
 * @category Class
 * @description Printed production attributes.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PrintSpec implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PrintSpec';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'colour' => 'string',
        'processes' => 'string[]',
        'sides' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'colour' => null,
        'processes' => null,
        'sides' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'colour' => false,
        'processes' => false,
        'sides' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'colour' => 'colour',
        'processes' => 'processes',
        'sides' => 'sides'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'colour' => 'setColour',
        'processes' => 'setProcesses',
        'sides' => 'setSides'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'colour' => 'getColour',
        'processes' => 'getProcesses',
        'sides' => 'getSides'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const COLOUR_MONO = 'mono';
    public const COLOUR_FULL_COLOUR = 'full_colour';
    public const COLOUR_SPOT = 'spot';
    public const COLOUR_UNKNOWN = 'unknown';
    public const PROCESSES_DIGITAL_PRINT = 'digital_print';
    public const PROCESSES_OFFSET_LITHO = 'offset_litho';
    public const PROCESSES_LARGE_FORMAT = 'large_format';
    public const PROCESSES_DTG = 'dtg';
    public const PROCESSES_DTF = 'dtf';
    public const PROCESSES_HTV = 'htv';
    public const PROCESSES_EMBROIDERY = 'embroidery';
    public const PROCESSES_SCREEN_PRINT = 'screen_print';
    public const PROCESSES_SUBLIMATION = 'sublimation';
    public const PROCESSES_DIGITAL_TEXTILE_PRINT = 'digital_textile_print';
    public const PROCESSES_REACTIVE_DYE_PRINT = 'reactive_dye_print';
    public const PROCESSES_PIGMENT_PRINT = 'pigment_print';
    public const PROCESSES_SEWING = 'sewing';
    public const PROCESSES_HEMMING = 'hemming';
    public const PROCESSES_PAD_PRINT = 'pad_print';
    public const PROCESSES_UV_PRINT = 'uv_print';
    public const PROCESSES_ENGRAVING = 'engraving';
    public const PROCESSES_LASER_ENGRAVING = 'laser_engraving';
    public const PROCESSES_CUTTING = 'cutting';
    public const PROCESSES_FOLDING = 'folding';
    public const PROCESSES_BINDING = 'binding';
    public const PROCESSES_LAMINATION = 'lamination';
    public const PROCESSES_FOILING = 'foiling';
    public const PROCESSES_SPOT_UV = 'spot_uv';
    public const PROCESSES_UNKNOWN = 'unknown';
    public const SIDES_SINGLE_SIDED = 'single_sided';
    public const SIDES_DOUBLE_SIDED = 'double_sided';
    public const SIDES_UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getColourAllowableValues()
    {
        return [
            self::COLOUR_MONO,
            self::COLOUR_FULL_COLOUR,
            self::COLOUR_SPOT,
            self::COLOUR_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProcessesAllowableValues()
    {
        return [
            self::PROCESSES_DIGITAL_PRINT,
            self::PROCESSES_OFFSET_LITHO,
            self::PROCESSES_LARGE_FORMAT,
            self::PROCESSES_DTG,
            self::PROCESSES_DTF,
            self::PROCESSES_HTV,
            self::PROCESSES_EMBROIDERY,
            self::PROCESSES_SCREEN_PRINT,
            self::PROCESSES_SUBLIMATION,
            self::PROCESSES_DIGITAL_TEXTILE_PRINT,
            self::PROCESSES_REACTIVE_DYE_PRINT,
            self::PROCESSES_PIGMENT_PRINT,
            self::PROCESSES_SEWING,
            self::PROCESSES_HEMMING,
            self::PROCESSES_PAD_PRINT,
            self::PROCESSES_UV_PRINT,
            self::PROCESSES_ENGRAVING,
            self::PROCESSES_LASER_ENGRAVING,
            self::PROCESSES_CUTTING,
            self::PROCESSES_FOLDING,
            self::PROCESSES_BINDING,
            self::PROCESSES_LAMINATION,
            self::PROCESSES_FOILING,
            self::PROCESSES_SPOT_UV,
            self::PROCESSES_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSidesAllowableValues()
    {
        return [
            self::SIDES_SINGLE_SIDED,
            self::SIDES_DOUBLE_SIDED,
            self::SIDES_UNKNOWN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('colour', $data ?? [], 'unknown');
        $this->setIfExists('processes', $data ?? [], null);
        $this->setIfExists('sides', $data ?? [], 'unknown');
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getColourAllowableValues();
        if (!is_null($this->container['colour']) && !in_array($this->container['colour'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'colour', must be one of '%s'",
                $this->container['colour'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSidesAllowableValues();
        if (!is_null($this->container['sides']) && !in_array($this->container['sides'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sides', must be one of '%s'",
                $this->container['sides'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets colour
     *
     * @return string|null
     */
    public function getColour()
    {
        return $this->container['colour'];
    }

    /**
     * Sets colour
     *
     * @param string|null $colour colour
     *
     * @return self
     */
    public function setColour($colour)
    {
        if (is_null($colour)) {
            throw new \InvalidArgumentException('non-nullable colour cannot be null');
        }
        $allowedValues = $this->getColourAllowableValues();
        if (!in_array($colour, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'colour', must be one of '%s'",
                    $colour,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['colour'] = $colour;

        return $this;
    }

    /**
     * Gets processes
     *
     * @return string[]|null
     */
    public function getProcesses()
    {
        return $this->container['processes'];
    }

    /**
     * Sets processes
     *
     * @param string[]|null $processes processes
     *
     * @return self
     */
    public function setProcesses($processes)
    {
        if (is_null($processes)) {
            throw new \InvalidArgumentException('non-nullable processes cannot be null');
        }
        $allowedValues = $this->getProcessesAllowableValues();
        if (array_diff($processes, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'processes', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['processes'] = $processes;

        return $this;
    }

    /**
     * Gets sides
     *
     * @return string|null
     */
    public function getSides()
    {
        return $this->container['sides'];
    }

    /**
     * Sets sides
     *
     * @param string|null $sides sides
     *
     * @return self
     */
    public function setSides($sides)
    {
        if (is_null($sides)) {
            throw new \InvalidArgumentException('non-nullable sides cannot be null');
        }
        $allowedValues = $this->getSidesAllowableValues();
        if (!in_array($sides, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sides', must be one of '%s'",
                    $sides,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sides'] = $sides;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
