<?php
/**
 * ProductPackResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * ProductPackResponse Class Doc Comment
 *
 * @category Class
 * @description Review-only product pack before canonical specification.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProductPackResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ProductPackResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'benchmark_references' => '\Jawwws\Gnaww\Model\ProductPackBenchmarkReference[]',
        'canonical_specifications_created' => 'bool',
        'clarifications' => '\Jawwws\Gnaww\Model\ProductPackClarification[]',
        'classification' => '\Jawwws\Gnaww\Model\IntentClassificationResponse',
        'confirmed_availability' => 'bool',
        'core_recommendations' => '\Jawwws\Gnaww\Model\ProductPackRecommendation[]',
        'deterministic_grounding' => 'bool',
        'excluded_recommendations' => '\Jawwws\Gnaww\Model\ProductPackRecommendation[]',
        'grounding_status' => 'string',
        'live_pricing_available' => 'bool',
        'no_benchmark_reason' => 'string',
        'optional_recommendations' => '\Jawwws\Gnaww\Model\ProductPackRecommendation[]',
        'producer_selection_performed' => 'bool',
        'provider_metadata' => '\Jawwws\Gnaww\Model\IntentProviderMetadata',
        'schema_name' => 'string',
        'schema_version' => 'string',
        'source' => '\Jawwws\Gnaww\Model\SourceInput',
        'specmatch_performed' => 'bool',
        'status' => 'string',
        'summary' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'benchmark_references' => null,
        'canonical_specifications_created' => null,
        'clarifications' => null,
        'classification' => null,
        'confirmed_availability' => null,
        'core_recommendations' => null,
        'deterministic_grounding' => null,
        'excluded_recommendations' => null,
        'grounding_status' => null,
        'live_pricing_available' => null,
        'no_benchmark_reason' => null,
        'optional_recommendations' => null,
        'producer_selection_performed' => null,
        'provider_metadata' => null,
        'schema_name' => null,
        'schema_version' => null,
        'source' => null,
        'specmatch_performed' => null,
        'status' => null,
        'summary' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'benchmark_references' => false,
        'canonical_specifications_created' => false,
        'clarifications' => false,
        'classification' => false,
        'confirmed_availability' => false,
        'core_recommendations' => false,
        'deterministic_grounding' => false,
        'excluded_recommendations' => false,
        'grounding_status' => false,
        'live_pricing_available' => false,
        'no_benchmark_reason' => true,
        'optional_recommendations' => false,
        'producer_selection_performed' => false,
        'provider_metadata' => false,
        'schema_name' => false,
        'schema_version' => false,
        'source' => false,
        'specmatch_performed' => false,
        'status' => false,
        'summary' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'benchmark_references' => 'benchmark_references',
        'canonical_specifications_created' => 'canonical_specifications_created',
        'clarifications' => 'clarifications',
        'classification' => 'classification',
        'confirmed_availability' => 'confirmed_availability',
        'core_recommendations' => 'core_recommendations',
        'deterministic_grounding' => 'deterministic_grounding',
        'excluded_recommendations' => 'excluded_recommendations',
        'grounding_status' => 'grounding_status',
        'live_pricing_available' => 'live_pricing_available',
        'no_benchmark_reason' => 'no_benchmark_reason',
        'optional_recommendations' => 'optional_recommendations',
        'producer_selection_performed' => 'producer_selection_performed',
        'provider_metadata' => 'provider_metadata',
        'schema_name' => 'schema_name',
        'schema_version' => 'schema_version',
        'source' => 'source',
        'specmatch_performed' => 'specmatch_performed',
        'status' => 'status',
        'summary' => 'summary'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'benchmark_references' => 'setBenchmarkReferences',
        'canonical_specifications_created' => 'setCanonicalSpecificationsCreated',
        'clarifications' => 'setClarifications',
        'classification' => 'setClassification',
        'confirmed_availability' => 'setConfirmedAvailability',
        'core_recommendations' => 'setCoreRecommendations',
        'deterministic_grounding' => 'setDeterministicGrounding',
        'excluded_recommendations' => 'setExcludedRecommendations',
        'grounding_status' => 'setGroundingStatus',
        'live_pricing_available' => 'setLivePricingAvailable',
        'no_benchmark_reason' => 'setNoBenchmarkReason',
        'optional_recommendations' => 'setOptionalRecommendations',
        'producer_selection_performed' => 'setProducerSelectionPerformed',
        'provider_metadata' => 'setProviderMetadata',
        'schema_name' => 'setSchemaName',
        'schema_version' => 'setSchemaVersion',
        'source' => 'setSource',
        'specmatch_performed' => 'setSpecmatchPerformed',
        'status' => 'setStatus',
        'summary' => 'setSummary'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'benchmark_references' => 'getBenchmarkReferences',
        'canonical_specifications_created' => 'getCanonicalSpecificationsCreated',
        'clarifications' => 'getClarifications',
        'classification' => 'getClassification',
        'confirmed_availability' => 'getConfirmedAvailability',
        'core_recommendations' => 'getCoreRecommendations',
        'deterministic_grounding' => 'getDeterministicGrounding',
        'excluded_recommendations' => 'getExcludedRecommendations',
        'grounding_status' => 'getGroundingStatus',
        'live_pricing_available' => 'getLivePricingAvailable',
        'no_benchmark_reason' => 'getNoBenchmarkReason',
        'optional_recommendations' => 'getOptionalRecommendations',
        'producer_selection_performed' => 'getProducerSelectionPerformed',
        'provider_metadata' => 'getProviderMetadata',
        'schema_name' => 'getSchemaName',
        'schema_version' => 'getSchemaVersion',
        'source' => 'getSource',
        'specmatch_performed' => 'getSpecmatchPerformed',
        'status' => 'getStatus',
        'summary' => 'getSummary'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CANONICAL_SPECIFICATIONS_CREATED_FALSE = 'false';
    public const CONFIRMED_AVAILABILITY_FALSE = 'false';
    public const DETERMINISTIC_GROUNDING_TRUE = 'true';
    public const GROUNDING_STATUS_GROUNDED = 'grounded';
    public const GROUNDING_STATUS_PARTIALLY_GROUNDED = 'partially_grounded';
    public const GROUNDING_STATUS_UNGROUNDED = 'ungrounded';
    public const LIVE_PRICING_AVAILABLE_FALSE = 'false';
    public const PRODUCER_SELECTION_PERFORMED_FALSE = 'false';
    public const SCHEMA_NAME_JAWWWS_PRODUCT_PACK_RESPONSE = 'jawwws.product_pack_response';
    public const SPECMATCH_PERFORMED_FALSE = 'false';
    public const STATUS_NEEDS_REVIEW = 'needs_review';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCanonicalSpecificationsCreatedAllowableValues()
    {
        return [
            self::CANONICAL_SPECIFICATIONS_CREATED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getConfirmedAvailabilityAllowableValues()
    {
        return [
            self::CONFIRMED_AVAILABILITY_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeterministicGroundingAllowableValues()
    {
        return [
            self::DETERMINISTIC_GROUNDING_TRUE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGroundingStatusAllowableValues()
    {
        return [
            self::GROUNDING_STATUS_GROUNDED,
            self::GROUNDING_STATUS_PARTIALLY_GROUNDED,
            self::GROUNDING_STATUS_UNGROUNDED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLivePricingAvailableAllowableValues()
    {
        return [
            self::LIVE_PRICING_AVAILABLE_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProducerSelectionPerformedAllowableValues()
    {
        return [
            self::PRODUCER_SELECTION_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemaNameAllowableValues()
    {
        return [
            self::SCHEMA_NAME_JAWWWS_PRODUCT_PACK_RESPONSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSpecmatchPerformedAllowableValues()
    {
        return [
            self::SPECMATCH_PERFORMED_FALSE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_NEEDS_REVIEW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('benchmark_references', $data ?? [], null);
        $this->setIfExists('canonical_specifications_created', $data ?? [], false);
        $this->setIfExists('clarifications', $data ?? [], null);
        $this->setIfExists('classification', $data ?? [], null);
        $this->setIfExists('confirmed_availability', $data ?? [], false);
        $this->setIfExists('core_recommendations', $data ?? [], null);
        $this->setIfExists('deterministic_grounding', $data ?? [], true);
        $this->setIfExists('excluded_recommendations', $data ?? [], null);
        $this->setIfExists('grounding_status', $data ?? [], null);
        $this->setIfExists('live_pricing_available', $data ?? [], false);
        $this->setIfExists('no_benchmark_reason', $data ?? [], null);
        $this->setIfExists('optional_recommendations', $data ?? [], null);
        $this->setIfExists('producer_selection_performed', $data ?? [], false);
        $this->setIfExists('provider_metadata', $data ?? [], null);
        $this->setIfExists('schema_name', $data ?? [], 'jawwws.product_pack_response');
        $this->setIfExists('schema_version', $data ?? [], '0.1');
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('specmatch_performed', $data ?? [], false);
        $this->setIfExists('status', $data ?? [], 'needs_review');
        $this->setIfExists('summary', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCanonicalSpecificationsCreatedAllowableValues();
        if (!is_null($this->container['canonical_specifications_created']) && !in_array($this->container['canonical_specifications_created'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'canonical_specifications_created', must be one of '%s'",
                $this->container['canonical_specifications_created'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['classification'] === null) {
            $invalidProperties[] = "'classification' can't be null";
        }
        $allowedValues = $this->getConfirmedAvailabilityAllowableValues();
        if (!is_null($this->container['confirmed_availability']) && !in_array($this->container['confirmed_availability'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'confirmed_availability', must be one of '%s'",
                $this->container['confirmed_availability'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDeterministicGroundingAllowableValues();
        if (!is_null($this->container['deterministic_grounding']) && !in_array($this->container['deterministic_grounding'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'deterministic_grounding', must be one of '%s'",
                $this->container['deterministic_grounding'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['grounding_status'] === null) {
            $invalidProperties[] = "'grounding_status' can't be null";
        }
        $allowedValues = $this->getGroundingStatusAllowableValues();
        if (!is_null($this->container['grounding_status']) && !in_array($this->container['grounding_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'grounding_status', must be one of '%s'",
                $this->container['grounding_status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLivePricingAvailableAllowableValues();
        if (!is_null($this->container['live_pricing_available']) && !in_array($this->container['live_pricing_available'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'live_pricing_available', must be one of '%s'",
                $this->container['live_pricing_available'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!is_null($this->container['producer_selection_performed']) && !in_array($this->container['producer_selection_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                $this->container['producer_selection_performed'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['provider_metadata'] === null) {
            $invalidProperties[] = "'provider_metadata' can't be null";
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!is_null($this->container['schema_name']) && !in_array($this->container['schema_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'schema_name', must be one of '%s'",
                $this->container['schema_name'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!is_null($this->container['specmatch_performed']) && !in_array($this->container['specmatch_performed'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                $this->container['specmatch_performed'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['summary'] === null) {
            $invalidProperties[] = "'summary' can't be null";
        }
        if ((mb_strlen($this->container['summary']) < 1)) {
            $invalidProperties[] = "invalid value for 'summary', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets benchmark_references
     *
     * @return \Jawwws\Gnaww\Model\ProductPackBenchmarkReference[]|null
     */
    public function getBenchmarkReferences()
    {
        return $this->container['benchmark_references'];
    }

    /**
     * Sets benchmark_references
     *
     * @param \Jawwws\Gnaww\Model\ProductPackBenchmarkReference[]|null $benchmark_references benchmark_references
     *
     * @return self
     */
    public function setBenchmarkReferences($benchmark_references)
    {
        if (is_null($benchmark_references)) {
            throw new \InvalidArgumentException('non-nullable benchmark_references cannot be null');
        }
        $this->container['benchmark_references'] = $benchmark_references;

        return $this;
    }

    /**
     * Gets canonical_specifications_created
     *
     * @return bool|null
     */
    public function getCanonicalSpecificationsCreated()
    {
        return $this->container['canonical_specifications_created'];
    }

    /**
     * Sets canonical_specifications_created
     *
     * @param bool|null $canonical_specifications_created canonical_specifications_created
     *
     * @return self
     */
    public function setCanonicalSpecificationsCreated($canonical_specifications_created)
    {
        if (is_null($canonical_specifications_created)) {
            throw new \InvalidArgumentException('non-nullable canonical_specifications_created cannot be null');
        }
        $allowedValues = $this->getCanonicalSpecificationsCreatedAllowableValues();
        if (!in_array($canonical_specifications_created, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'canonical_specifications_created', must be one of '%s'",
                    $canonical_specifications_created,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['canonical_specifications_created'] = $canonical_specifications_created;

        return $this;
    }

    /**
     * Gets clarifications
     *
     * @return \Jawwws\Gnaww\Model\ProductPackClarification[]|null
     */
    public function getClarifications()
    {
        return $this->container['clarifications'];
    }

    /**
     * Sets clarifications
     *
     * @param \Jawwws\Gnaww\Model\ProductPackClarification[]|null $clarifications clarifications
     *
     * @return self
     */
    public function setClarifications($clarifications)
    {
        if (is_null($clarifications)) {
            throw new \InvalidArgumentException('non-nullable clarifications cannot be null');
        }
        $this->container['clarifications'] = $clarifications;

        return $this;
    }

    /**
     * Gets classification
     *
     * @return \Jawwws\Gnaww\Model\IntentClassificationResponse
     */
    public function getClassification()
    {
        return $this->container['classification'];
    }

    /**
     * Sets classification
     *
     * @param \Jawwws\Gnaww\Model\IntentClassificationResponse $classification classification
     *
     * @return self
     */
    public function setClassification($classification)
    {
        if (is_null($classification)) {
            throw new \InvalidArgumentException('non-nullable classification cannot be null');
        }
        $this->container['classification'] = $classification;

        return $this;
    }

    /**
     * Gets confirmed_availability
     *
     * @return bool|null
     */
    public function getConfirmedAvailability()
    {
        return $this->container['confirmed_availability'];
    }

    /**
     * Sets confirmed_availability
     *
     * @param bool|null $confirmed_availability confirmed_availability
     *
     * @return self
     */
    public function setConfirmedAvailability($confirmed_availability)
    {
        if (is_null($confirmed_availability)) {
            throw new \InvalidArgumentException('non-nullable confirmed_availability cannot be null');
        }
        $allowedValues = $this->getConfirmedAvailabilityAllowableValues();
        if (!in_array($confirmed_availability, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'confirmed_availability', must be one of '%s'",
                    $confirmed_availability,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['confirmed_availability'] = $confirmed_availability;

        return $this;
    }

    /**
     * Gets core_recommendations
     *
     * @return \Jawwws\Gnaww\Model\ProductPackRecommendation[]|null
     */
    public function getCoreRecommendations()
    {
        return $this->container['core_recommendations'];
    }

    /**
     * Sets core_recommendations
     *
     * @param \Jawwws\Gnaww\Model\ProductPackRecommendation[]|null $core_recommendations core_recommendations
     *
     * @return self
     */
    public function setCoreRecommendations($core_recommendations)
    {
        if (is_null($core_recommendations)) {
            throw new \InvalidArgumentException('non-nullable core_recommendations cannot be null');
        }
        $this->container['core_recommendations'] = $core_recommendations;

        return $this;
    }

    /**
     * Gets deterministic_grounding
     *
     * @return bool|null
     */
    public function getDeterministicGrounding()
    {
        return $this->container['deterministic_grounding'];
    }

    /**
     * Sets deterministic_grounding
     *
     * @param bool|null $deterministic_grounding deterministic_grounding
     *
     * @return self
     */
    public function setDeterministicGrounding($deterministic_grounding)
    {
        if (is_null($deterministic_grounding)) {
            throw new \InvalidArgumentException('non-nullable deterministic_grounding cannot be null');
        }
        $allowedValues = $this->getDeterministicGroundingAllowableValues();
        if (!in_array($deterministic_grounding, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'deterministic_grounding', must be one of '%s'",
                    $deterministic_grounding,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['deterministic_grounding'] = $deterministic_grounding;

        return $this;
    }

    /**
     * Gets excluded_recommendations
     *
     * @return \Jawwws\Gnaww\Model\ProductPackRecommendation[]|null
     */
    public function getExcludedRecommendations()
    {
        return $this->container['excluded_recommendations'];
    }

    /**
     * Sets excluded_recommendations
     *
     * @param \Jawwws\Gnaww\Model\ProductPackRecommendation[]|null $excluded_recommendations excluded_recommendations
     *
     * @return self
     */
    public function setExcludedRecommendations($excluded_recommendations)
    {
        if (is_null($excluded_recommendations)) {
            throw new \InvalidArgumentException('non-nullable excluded_recommendations cannot be null');
        }
        $this->container['excluded_recommendations'] = $excluded_recommendations;

        return $this;
    }

    /**
     * Gets grounding_status
     *
     * @return string
     */
    public function getGroundingStatus()
    {
        return $this->container['grounding_status'];
    }

    /**
     * Sets grounding_status
     *
     * @param string $grounding_status grounding_status
     *
     * @return self
     */
    public function setGroundingStatus($grounding_status)
    {
        if (is_null($grounding_status)) {
            throw new \InvalidArgumentException('non-nullable grounding_status cannot be null');
        }
        $allowedValues = $this->getGroundingStatusAllowableValues();
        if (!in_array($grounding_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'grounding_status', must be one of '%s'",
                    $grounding_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['grounding_status'] = $grounding_status;

        return $this;
    }

    /**
     * Gets live_pricing_available
     *
     * @return bool|null
     */
    public function getLivePricingAvailable()
    {
        return $this->container['live_pricing_available'];
    }

    /**
     * Sets live_pricing_available
     *
     * @param bool|null $live_pricing_available live_pricing_available
     *
     * @return self
     */
    public function setLivePricingAvailable($live_pricing_available)
    {
        if (is_null($live_pricing_available)) {
            throw new \InvalidArgumentException('non-nullable live_pricing_available cannot be null');
        }
        $allowedValues = $this->getLivePricingAvailableAllowableValues();
        if (!in_array($live_pricing_available, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'live_pricing_available', must be one of '%s'",
                    $live_pricing_available,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['live_pricing_available'] = $live_pricing_available;

        return $this;
    }

    /**
     * Gets no_benchmark_reason
     *
     * @return string|null
     */
    public function getNoBenchmarkReason()
    {
        return $this->container['no_benchmark_reason'];
    }

    /**
     * Sets no_benchmark_reason
     *
     * @param string|null $no_benchmark_reason no_benchmark_reason
     *
     * @return self
     */
    public function setNoBenchmarkReason($no_benchmark_reason)
    {
        if (is_null($no_benchmark_reason)) {
            array_push($this->openAPINullablesSetToNull, 'no_benchmark_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('no_benchmark_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['no_benchmark_reason'] = $no_benchmark_reason;

        return $this;
    }

    /**
     * Gets optional_recommendations
     *
     * @return \Jawwws\Gnaww\Model\ProductPackRecommendation[]|null
     */
    public function getOptionalRecommendations()
    {
        return $this->container['optional_recommendations'];
    }

    /**
     * Sets optional_recommendations
     *
     * @param \Jawwws\Gnaww\Model\ProductPackRecommendation[]|null $optional_recommendations optional_recommendations
     *
     * @return self
     */
    public function setOptionalRecommendations($optional_recommendations)
    {
        if (is_null($optional_recommendations)) {
            throw new \InvalidArgumentException('non-nullable optional_recommendations cannot be null');
        }
        $this->container['optional_recommendations'] = $optional_recommendations;

        return $this;
    }

    /**
     * Gets producer_selection_performed
     *
     * @return bool|null
     */
    public function getProducerSelectionPerformed()
    {
        return $this->container['producer_selection_performed'];
    }

    /**
     * Sets producer_selection_performed
     *
     * @param bool|null $producer_selection_performed producer_selection_performed
     *
     * @return self
     */
    public function setProducerSelectionPerformed($producer_selection_performed)
    {
        if (is_null($producer_selection_performed)) {
            throw new \InvalidArgumentException('non-nullable producer_selection_performed cannot be null');
        }
        $allowedValues = $this->getProducerSelectionPerformedAllowableValues();
        if (!in_array($producer_selection_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'producer_selection_performed', must be one of '%s'",
                    $producer_selection_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['producer_selection_performed'] = $producer_selection_performed;

        return $this;
    }

    /**
     * Gets provider_metadata
     *
     * @return \Jawwws\Gnaww\Model\IntentProviderMetadata
     */
    public function getProviderMetadata()
    {
        return $this->container['provider_metadata'];
    }

    /**
     * Sets provider_metadata
     *
     * @param \Jawwws\Gnaww\Model\IntentProviderMetadata $provider_metadata provider_metadata
     *
     * @return self
     */
    public function setProviderMetadata($provider_metadata)
    {
        if (is_null($provider_metadata)) {
            throw new \InvalidArgumentException('non-nullable provider_metadata cannot be null');
        }
        $this->container['provider_metadata'] = $provider_metadata;

        return $this;
    }

    /**
     * Gets schema_name
     *
     * @return string|null
     */
    public function getSchemaName()
    {
        return $this->container['schema_name'];
    }

    /**
     * Sets schema_name
     *
     * @param string|null $schema_name schema_name
     *
     * @return self
     */
    public function setSchemaName($schema_name)
    {
        if (is_null($schema_name)) {
            throw new \InvalidArgumentException('non-nullable schema_name cannot be null');
        }
        $allowedValues = $this->getSchemaNameAllowableValues();
        if (!in_array($schema_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'schema_name', must be one of '%s'",
                    $schema_name,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['schema_name'] = $schema_name;

        return $this;
    }

    /**
     * Gets schema_version
     *
     * @return string|null
     */
    public function getSchemaVersion()
    {
        return $this->container['schema_version'];
    }

    /**
     * Sets schema_version
     *
     * @param string|null $schema_version schema_version
     *
     * @return self
     */
    public function setSchemaVersion($schema_version)
    {
        if (is_null($schema_version)) {
            throw new \InvalidArgumentException('non-nullable schema_version cannot be null');
        }
        $this->container['schema_version'] = $schema_version;

        return $this;
    }

    /**
     * Gets source
     *
     * @return \Jawwws\Gnaww\Model\SourceInput
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param \Jawwws\Gnaww\Model\SourceInput $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets specmatch_performed
     *
     * @return bool|null
     */
    public function getSpecmatchPerformed()
    {
        return $this->container['specmatch_performed'];
    }

    /**
     * Sets specmatch_performed
     *
     * @param bool|null $specmatch_performed specmatch_performed
     *
     * @return self
     */
    public function setSpecmatchPerformed($specmatch_performed)
    {
        if (is_null($specmatch_performed)) {
            throw new \InvalidArgumentException('non-nullable specmatch_performed cannot be null');
        }
        $allowedValues = $this->getSpecmatchPerformedAllowableValues();
        if (!in_array($specmatch_performed, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'specmatch_performed', must be one of '%s'",
                    $specmatch_performed,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['specmatch_performed'] = $specmatch_performed;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets summary
     *
     * @return string
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param string $summary summary
     *
     * @return self
     */
    public function setSummary($summary)
    {
        if (is_null($summary)) {
            throw new \InvalidArgumentException('non-nullable summary cannot be null');
        }

        if ((mb_strlen($summary) < 1)) {
            throw new \InvalidArgumentException('invalid length for $summary when calling ProductPackResponse., must be bigger than or equal to 1.');
        }

        $this->container['summary'] = $summary;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
