<?php
/**
 * ResolvedRecipeMatchState
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 */

/**
 * Gnaww Developer API
 *
 * Reviewed public print-intelligence contract for direct HTTP, CLI, SDK and MCP consumers. Capability fit is not price, live availability, producer acceptance or an order.
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://gnaww-sdk.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto Gnaww SDK.
 * https://gnaww-sdk.tech
 * Do not edit the class manually.
 */

namespace Jawwws\Gnaww\Model;

use \ArrayAccess;
use \Jawwws\Gnaww\ObjectSerializer;

/**
 * ResolvedRecipeMatchState Class Doc Comment
 *
 * @category Class
 * @description Safe persisted Recipe identity carried by a resolved-Recipe match.
 * @package  Jawwws\Gnaww
 * @author   Gnaww SDK team
 * @link     https://gnaww-sdk.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResolvedRecipeMatchState implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ResolvedRecipeMatchState';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'canonicalisation_version' => 'string',
        'persisted' => 'bool',
        'recipe_id' => 'string',
        'recipe_schema_name' => 'string',
        'recipe_schema_version' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'canonicalisation_version' => null,
        'persisted' => null,
        'recipe_id' => null,
        'recipe_schema_name' => null,
        'recipe_schema_version' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'canonicalisation_version' => false,
        'persisted' => false,
        'recipe_id' => false,
        'recipe_schema_name' => false,
        'recipe_schema_version' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'canonicalisation_version' => 'canonicalisation_version',
        'persisted' => 'persisted',
        'recipe_id' => 'recipe_id',
        'recipe_schema_name' => 'recipe_schema_name',
        'recipe_schema_version' => 'recipe_schema_version'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'canonicalisation_version' => 'setCanonicalisationVersion',
        'persisted' => 'setPersisted',
        'recipe_id' => 'setRecipeId',
        'recipe_schema_name' => 'setRecipeSchemaName',
        'recipe_schema_version' => 'setRecipeSchemaVersion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'canonicalisation_version' => 'getCanonicalisationVersion',
        'persisted' => 'getPersisted',
        'recipe_id' => 'getRecipeId',
        'recipe_schema_name' => 'getRecipeSchemaName',
        'recipe_schema_version' => 'getRecipeSchemaVersion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PERSISTED_TRUE = 'true';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPersistedAllowableValues()
    {
        return [
            self::PERSISTED_TRUE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('canonicalisation_version', $data ?? [], null);
        $this->setIfExists('persisted', $data ?? [], true);
        $this->setIfExists('recipe_id', $data ?? [], null);
        $this->setIfExists('recipe_schema_name', $data ?? [], null);
        $this->setIfExists('recipe_schema_version', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['canonicalisation_version'] === null) {
            $invalidProperties[] = "'canonicalisation_version' can't be null";
        }
        if ((mb_strlen($this->container['canonicalisation_version']) < 1)) {
            $invalidProperties[] = "invalid value for 'canonicalisation_version', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getPersistedAllowableValues();
        if (!is_null($this->container['persisted']) && !in_array($this->container['persisted'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'persisted', must be one of '%s'",
                $this->container['persisted'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['recipe_id'] === null) {
            $invalidProperties[] = "'recipe_id' can't be null";
        }
        if (!preg_match("/^GNR-[0-9A-HJKMNP-TV-Z]{26}$/", $this->container['recipe_id'])) {
            $invalidProperties[] = "invalid value for 'recipe_id', must be conform to the pattern /^GNR-[0-9A-HJKMNP-TV-Z]{26}$/.";
        }

        if ($this->container['recipe_schema_name'] === null) {
            $invalidProperties[] = "'recipe_schema_name' can't be null";
        }
        if ((mb_strlen($this->container['recipe_schema_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'recipe_schema_name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['recipe_schema_version'] === null) {
            $invalidProperties[] = "'recipe_schema_version' can't be null";
        }
        if ((mb_strlen($this->container['recipe_schema_version']) < 1)) {
            $invalidProperties[] = "invalid value for 'recipe_schema_version', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets canonicalisation_version
     *
     * @return string
     */
    public function getCanonicalisationVersion()
    {
        return $this->container['canonicalisation_version'];
    }

    /**
     * Sets canonicalisation_version
     *
     * @param string $canonicalisation_version canonicalisation_version
     *
     * @return self
     */
    public function setCanonicalisationVersion($canonicalisation_version)
    {
        if (is_null($canonicalisation_version)) {
            throw new \InvalidArgumentException('non-nullable canonicalisation_version cannot be null');
        }

        if ((mb_strlen($canonicalisation_version) < 1)) {
            throw new \InvalidArgumentException('invalid length for $canonicalisation_version when calling ResolvedRecipeMatchState., must be bigger than or equal to 1.');
        }

        $this->container['canonicalisation_version'] = $canonicalisation_version;

        return $this;
    }

    /**
     * Gets persisted
     *
     * @return bool|null
     */
    public function getPersisted()
    {
        return $this->container['persisted'];
    }

    /**
     * Sets persisted
     *
     * @param bool|null $persisted persisted
     *
     * @return self
     */
    public function setPersisted($persisted)
    {
        if (is_null($persisted)) {
            throw new \InvalidArgumentException('non-nullable persisted cannot be null');
        }
        $allowedValues = $this->getPersistedAllowableValues();
        if (!in_array($persisted, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'persisted', must be one of '%s'",
                    $persisted,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['persisted'] = $persisted;

        return $this;
    }

    /**
     * Gets recipe_id
     *
     * @return string
     */
    public function getRecipeId()
    {
        return $this->container['recipe_id'];
    }

    /**
     * Sets recipe_id
     *
     * @param string $recipe_id recipe_id
     *
     * @return self
     */
    public function setRecipeId($recipe_id)
    {
        if (is_null($recipe_id)) {
            throw new \InvalidArgumentException('non-nullable recipe_id cannot be null');
        }

        if ((!preg_match("/^GNR-[0-9A-HJKMNP-TV-Z]{26}$/", ObjectSerializer::toString($recipe_id)))) {
            throw new \InvalidArgumentException("invalid value for \$recipe_id when calling ResolvedRecipeMatchState., must conform to the pattern /^GNR-[0-9A-HJKMNP-TV-Z]{26}$/.");
        }

        $this->container['recipe_id'] = $recipe_id;

        return $this;
    }

    /**
     * Gets recipe_schema_name
     *
     * @return string
     */
    public function getRecipeSchemaName()
    {
        return $this->container['recipe_schema_name'];
    }

    /**
     * Sets recipe_schema_name
     *
     * @param string $recipe_schema_name recipe_schema_name
     *
     * @return self
     */
    public function setRecipeSchemaName($recipe_schema_name)
    {
        if (is_null($recipe_schema_name)) {
            throw new \InvalidArgumentException('non-nullable recipe_schema_name cannot be null');
        }

        if ((mb_strlen($recipe_schema_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $recipe_schema_name when calling ResolvedRecipeMatchState., must be bigger than or equal to 1.');
        }

        $this->container['recipe_schema_name'] = $recipe_schema_name;

        return $this;
    }

    /**
     * Gets recipe_schema_version
     *
     * @return string
     */
    public function getRecipeSchemaVersion()
    {
        return $this->container['recipe_schema_version'];
    }

    /**
     * Sets recipe_schema_version
     *
     * @param string $recipe_schema_version recipe_schema_version
     *
     * @return self
     */
    public function setRecipeSchemaVersion($recipe_schema_version)
    {
        if (is_null($recipe_schema_version)) {
            throw new \InvalidArgumentException('non-nullable recipe_schema_version cannot be null');
        }

        if ((mb_strlen($recipe_schema_version) < 1)) {
            throw new \InvalidArgumentException('invalid length for $recipe_schema_version when calling ResolvedRecipeMatchState., must be bigger than or equal to 1.');
        }

        $this->container['recipe_schema_version'] = $recipe_schema_version;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
